### ISSUE TITLE
Limited amount items from the same users on the dashboard

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#102]
**Context**
As newcomer user on inventaire.io (loggedout) when I scroll down the page for the first time, i can see the last created items on the platform. 

**Problem:**
Those items often come from only one user who uploaded dozen of books 5 minutes before. 
This situation does not reflect the multiplicity of users on inventaire and tend to leave a image of an  platform with few active users.

**Suggested Solution:**
Only 3 (or x) items from the same user can be displayed

**Suggested Implementation:**
Query too many items for the dashboard, 
then group by users, 
map the groups to limit them to 3 items
join

**Comment by jum-s** [comment]
[`lastPublic`](https://github.com/inventaire/inventaire/blob/ab45b48428ef8171d29830f345177d9aacb38232/server/controllers/items/items.coffee#L14) could be renamed `recentSamples` and could be filtered either by

- number of users (< 5)
- categories of items (when [this ticket](https://trello.com/c/wq1RCyuc/20-sort-books-by-author-genre-collection-publication-date) is done)
- hand-pick a 100 'representative items' and display a sample of 15

**Comment by maxlath** [comment]
fixed by #109 server-side and https://github.com/inventaire/inventaire-client/commit/5060a67 client-side
