### ISSUE TITLE
allow to import an entity to Wikidata

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#104]
Entity requirements:
* requires that entity is free of claims to local entities
* requires that the user as an associated Wikidata account

Required interfaces:
* an API endpoint to trigger the import
* an "import to Wikidata" button on the entity edition page when the previous conditions are met

Post-import actions:
* merge the local entity in the newly created Wikidata entity to propagate the redirection to all related claims and items

**Comment by maxlath** [comment]
done in #225

**Comment by lucaswerkmeister** [comment]
Neat! Can I try it out already or is it not deployed yet?

**Comment by maxlath** [comment]
it was first deployed behind an admin flag, but now (9269daa8) only requires to be authentified and to have your Wikidata account connected

**Comment by lucaswerkmeister** [comment]
Hm, is this an API-only thing for now? I haven’t even found the option to link my Inventaire account to Wikidata yet.

**Comment by maxlath** [comment]
it's also on the client, but you weren't allowed to see it yesterday. Now, you should see a button on the top right of [this page](https://inventaire.io/entity/inv:e8da67ccc60fb837e0c31448d17bc67b/edit):
[![move_to_wd](https://user-images.githubusercontent.com/1596934/48066073-dbae2080-e1cc-11e8-8932-ba54fa5617fc.png)](https://inventaire.io/entity/inv:e8da67ccc60fb837e0c31448d17bc67b/edit)

If you click it but you never associated your Wikidata account before, it should invite you to do so, otherwise it should work directly.

In case you don't see the button, try emptying the browser cache: `Ctrl+Shift+R`

**Comment by lucaswerkmeister** [comment]
Alright, thanks! So it’s only available for works, not editions, for now?
