### ISSUE TITLE
Edition not found, but by ISBN

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#105]
As a user when i want to add an edition to my inventaire, I type the title, inventaire does not find an edition but it does find a work 
Example with Le déchronologue : 
![selection_001](https://user-images.githubusercontent.com/5363918/30022424-8d5dc7a8-916b-11e7-85bb-c3360ba16710.png)
the i select an edition through ISBN:
![selection_002](https://user-images.githubusercontent.com/5363918/30022507-e8c643e0-916b-11e7-9509-1614fdf8a3cb.png)
and i add it to my inventaire
![selection_003](https://user-images.githubusercontent.com/5363918/30022518-f54a8ab8-916b-11e7-8b4e-388a0bbd00da.png)

Nice, it works

BUT

Why when i do it again the work and the edition has not been linked together, why do i still have to type the ISBN. How could it be resolved so that, when i type a book title, it automatically find the work & the edition (since the problem has been resolved earlier by someone who linked edition and work)

**Comment by maxlath** [comment]
so the problem is that the live search doesn't show the edition or that the edition isn't visible on the work's page even after having added it?

**Comment by jum-s** [comment]
"edition isn't visible on the work's page even after having added it"
is it the merge request tool your using can be automated ?

**Comment by maxlath** [comment]
I can't reproduce the missing edition behavior :/

the merge tool I'm using is simply a curl request to the admin-only endpoint [`/api/entities?action=merge`](https://github.com/inventaire/inventaire/blob/6cd07d43a47afb67d2db9eeab2a775866210cafb/server/controllers/entities/entities.coffee#L32), it can't be fully automated as sometimes, users mistakenly suggest an ISBN for the wrong work

**Comment by jum-s** [comment]
thats more a client issue, and it is mainly because im invited to create a new entity too easly,
[#127](https://github.com/inventaire/inventaire-client/pull/127) actually solve the problem
