### ISSUE TITLE
link entity to Wikidata item

### ISSUE THREAD

**Issue by nichtich** [inventaire/inventaire#110]
If an entity is created on inventaire because it was missing in Wikidata, how to link it to Wikidata once there is an equivalent item there? e.g. the following are the same:

* <https://inventaire.io/entity/inv:a8f43fc184768b0ad5cbe0b1d4fa6291>
* <http://www.wikidata.org/entity/Q36366614>

maybe the more general issue is how to sync with updates on Wikidata.

**Comment by maxlath** [comment]
In this kind of cases (which happens quite often), we need to `merge` the `inv` entity into the `wd` one, [which is currently an admin task](https://github.com/inventaire/inventaire/blob/85e5ac7ff2c141aa2f3d4e10142e3028f8f6ce35/server/controllers/entities/entities.coffee#L35). We are lacking an interface to request a merge as a non admin, and a process to give merge rights to trustable users. Meanwhile, you can find a "signal an error" form at the bottom of the data editor page to request a merge:
![selection_003](https://user-images.githubusercontent.com/1596934/32144899-4d68ef1c-bcc0-11e7-91f0-f29371d96d4d.png)

I merged `inv:a8f43fc184768b0ad5cbe0b1d4fa6291` into `wd:Q36366614`

**Comment by maxlath** [comment]
related issue: #91
