### ISSUE TITLE
Show links from book to other catalogs

### ISSUE THREAD

**Issue by nichtich** [inventaire/inventaire#112]
Wikidata contains several [properties to identify books](http://www.wikidata.org/entity/Q29547399). Each property has an URL template to create links into the catalog via property values. See [this SPARQL query](http://tinyurl.com/yavzvhme) to get a list. On a book page, inventaire should show this links based on Wikidata, e.g. to directly get to the corresponding entry in Worldcat. Editing the links in inventaire is less relevant (or might be too complicated and users can do so in Wikidata).

**Comment by maxlath** [comment]
I don't think displaying all those links should be the default behavior, but having an easy to access them or an option to get them to be displayed could totally make sense. Could you add what you think are the relevant property ids to the list of [whitelisted properties](https://github.com/inventaire/inventaire/blob/7682569/server/lib/wikidata/whitelisted_properties.coffee)?

**Comment by salgo60** [comment]
One candidate is [Property:P3155](https://www.wikidata.org/wiki/Property:P3155) for Runeberg [electronic archive](http://runeberg.org/katalog.html)

**Comment by exilexi** [comment]
Especially interested in the Worldcat linking, so we can find public libraries nearby that we can lend the book from. Open Library does this, for instance.

**Comment by maxlath** [comment]
* Displayed links customization was added by https://github.com/inventaire/inventaire-client/pull/464
* Added P3155 and P243

To add more properties, check the opened [properties requests](https://github.com/inventaire/inventaire/labels/properties%20request) and if missing, open a [new issue](https://github.com/inventaire/inventaire/issues/new?title=add%20property%20xyz%20(wdt:Pxxx)&labels=properties%20request)
