### ISSUE TITLE
Add the ability to search in one's own book collection

### ISSUE THREAD

**Issue by pandark** [inventaire/inventaire#119]
It would be nice to be able to search in one's own book collection in the same way it is possible to search in the list of all public books.

**Comment by maxlath** [comment]
this could be done by querying the ElasticSearch items index with a `{ term: { owner: userId } }` filter

**Comment by thewholelifetolearn** [comment]
This issue is similar to https://github.com/inventaire/inventaire-client/issues/116

**Comment by maxlath** [comment]
yes, thanks @thewholelifetolearn for spotting it ^^
I'm closing that one and we can continue the conversation over there
