### ISSUE TITLE
allow access to a user public item

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#12]
ex:  see public items at `/inventory/username` when not connected

**Comment by Abbe98** [comment]
This should probably be done using a new public API action?

**Comment by Abbe98** [comment]
Or is it `api/items/public` that should be used?

**Comment by maxlath** [comment]
oh sorry, this issue has indeed already been fixed: you can now access any non-friend non-co-group-member profile and see the user public books

**Comment by maxlath** [comment]
and indeed it's the 'user-public-items' action that is being used

**Comment by Abbe98** [comment]
Then this is just not implanted on the client-side.
