### ISSUE TITLE
Invitation from an admin to join a group

### ISSUE THREAD

**Issue by pandark** [inventaire/inventaire#121]
I'd like to be able, as a group admin, to invite users to become members of this group, the same way friendship requests work (UI-wise).

**Comment by maxlath** [comment]
there is an group dashboard where you can invite people to join your group: https://inventaire.io/network/groups/settings
But it's currently limited to inviting contacts that are already friends, and it also miss the possibility to invite by email: is it what you are looking for?

**Comment by pandark** [comment]
Invite by username which are not already friends 🙂

(I know I'm not using the group in the way it's meant to be, since I can't share books with only friends or only a group and I will run into trouble at some point… 😄)

**Comment by maxlath** [comment]
[being able to share different books with your friends and your groups is a recurring feature request](https://trello.com/c/hVawMbmt/80-finer-sharing-parameters) so you might just be anticipating future developments ;)

**Comment by maxlath** [comment]
#125 and inventaire/inventaire-client#126 are in prod!
The two main update are accessible from the [group settings interface](https://inventaire.io/network/groups/user):
- invite any user to join the group
- invite anyone by email to join the group

Those two features are also accessible to non-admin users, does that fit your use-case?
