### ISSUE TITLE
Manage group members via the API

### ISSUE THREAD

**Issue by pandark** [inventaire/inventaire#122]
I'm trying to create a group for an organization which has it's own oauth/api thing.
I'd like to be able to accept (or invite) members to the group automatically, once they authenticate to an external app using that organization oauth and indicate their inventaire.io username, instead of having to manually accept each one of them.
4 suggested endpoints :
* accept a user in the group
* invite a user in the group (if they are not already in the group) see #121
* change the user role (admin/not admin) in the group
* remove a user from the group

**Comment by maxlath** [comment]
Most of those endpoints [already exist](https://github.com/inventaire/inventaire/blob/4e71e7d/server/controllers/groups/groups.coffee#L30) but are not documented on [api.inventaire.io](https://api.inventaire.io) yet, (and not that well documented in the code either), I will give it an update in the coming days.

Would that be ok in your use case to authentify those API requests with BasicAuth or cookies (the second one being faster btw) as [we don't provide OAuth yet](https://github.com/inventaire/inventaire/issues/84)?

**Comment by pandark** [comment]
Yep. As long as it's hosted on my own server and I am the only one working on the code, it's okayish to have my password in clear 🙂.

**Comment by maxlath** [comment]
done!
- [accept a user in the group](https://api.inventaire.io/#!/Groups/put_groups_action_accept)
- [invite a user in the group](https://api.inventaire.io/#!/Groups/put_groups_action_invite)
- [change the user role (admin/not admin) in the group](https://api.inventaire.io/#!/Groups/put_groups_action_make_admin)
- [remove a user from the group](https://api.inventaire.io/#!/Groups/put_groups_action_kick)

**Comment by jum-s** [comment]
done and documented nice !
