### ISSUE TITLE
cleaning entities

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#129]
Since inventaire entities dump is available through [dump](http://dumps.inventaire.io/) and [api](http://api.inventaire.io/) everyone can see how vast [errors and duplicates](https://inventaire.io/api/entities?action=search&search=Bilbo%20le%20hobbit&lang=fr) are, which is a good thing but can be suggested for merge.
In order to take care of those old seed, and prevent adding new ones.
Some [tools](https://hack.allmende.io/inv-collector#per-entity-cleaning) are described here.

**Comment by maxlath** [comment]
I had an illumination yesterday: we were discussing identifying works duplicates by matching works and authors labels with Wikidata entities labels, but I would expect that we don't find that many that way, as this matching approach is already done [during the dataseed-based automatic entities creation process](https://github.com/inventaire/inventaire/blob/bbc70f2/server/controllers/entities/lib/scaffold_entity_from_seed/search_work_entity_by_title_and_authors.coffee#L33-L37). We might find more by improving this matching process (comparing labels in different languages, trying to match using aliases, etc), and find some more. But a bigger source of duplicates is probably authors for which we got a match, but without being able to match the works: Wikidata knows many authors, but often miss many of their works (out of super famous classic authors for which hordes of fans created a Wikipedia article for each of their works).

A major collector task could thus be to identify authors that have a single homonym in Wikidata (low hanging fruits), and in a second time, authors that have several  homonyms.

**Comment by maxlath** [comment]
closing as too broad and now addressed by `tasks`
