### ISSUE TITLE
upgrade to CouchDB 2.x

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#149]
[The PPA we rely on](https://launchpad.net/~couchdb/+archive/ubuntu/stable) is blocked at 1.6.1, [with no update in sight](https://twitter.com/maxlath/status/929380246205452290), which forces us to stay a version with [known security issues](http://docs.couchdb.org/en/master/cve/2017-12635.html)

The easiest alternative would be to upgrade to 2.x:
* [*nix install](http://docs.couchdb.org/en/2.1.1/install/unix.html)
* [Upgrading from CouchDB 1.x](http://docs.couchdb.org/en/2.1.1/install/upgrading.html)
but I don't know the difficulties (libs compatibility?) we should expect

**Comment by jum-s** [comment]
couchdb is now on 3.1 see #418
