### ISSUE TITLE
https errors

### ISSUE THREAD

**Issue by pierreozoux** [inventaire/inventaire#15]
"mixed content" - gravatar, cdn
sha1 signature algo
...

Open javascript console for more :)

**Comment by maxlath** [comment]
Avoiding mixed content is a nice to have but was a bit let aside, compared to more urgent issues, but that should be on the todo list indeed.
Fixing mixed content would require several reworks on the way pictures are hosted and distributed:
- currently, as a temporary/kick-and-dirty solution, pictures may just be url pointing to other domains, notably gravatar
- I use a free-as-in-free-beer cdn - [cdn.filter.to](http://cdn.filter.to/) - which doesn't offer https. In addition, caching and compaction aren't optimal.

A solution for those two issue would be to
- host or re-host all pictures
- use a better cdn solution or run one

**Comment by pierreozoux** [comment]
gravatar has an https endpoint (my 2 cents)

**Comment by maxlath** [comment]
@pierreozoux for what is of the sha1 signature, it's just a matter of re-generating the key with a better algorithm right? Which algorithm would you recommend?

**Comment by pierreozoux** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=inventaire.io&s=92.222.64.49

You might ask Gandi if they can reissue one with a stronger signature?

**Comment by maxlath** [comment]
[this seems to be the usual certificate pain](https://www.gandi.net/news/en/2014-10-21/2460-sha-2_certificates_are_now_available/), I'm tempted to just wait for [letsencrypt.org](https://letsencrypt.org/) to be ready to make all that right with a free SHA-256 wildcard certificate

**Comment by pierreozoux** [comment]
The warning about your site (the orange https warning) is due to the fact that you have resources not behind https.

So maybe, this is the priority?

And yes, Let's encrypt will change the world \o/

**Comment by maxlath** [comment]
moved all the images behind inventaire.io/img so there shouldn't be mixed-content anymore!

remains the sha1 signature algo, I plan to handled this this Autumn at the certificate renewal

**Comment by ldidry** [comment]
> A solution for those two issue would be to
*  host or re-host all pictures

I don't know if it would be easy to integrate with Inventaire, but [Camo](https://github.com/atmos/camo) is an image proxy which can do the job:
* the external images URLs will be replaced by `yourserver.org/camo/foo/bar`
* camo get the images for you and serves the images => no mixed-content

**Comment by maxlath** [comment]
thanks @ldidry for the suggestion, I came to something of this kind indeed + resizing on the fly:
* hosted images: https://inventaire.io/img/150x150/65992f3f82ee6f9bd0b8b4c073e73785948acf24.jpg
* external images proxied: https://inventaire.io/img/300x300/10087418?href=http%3A%2F%2Fbooks.google.com%2Fbooks%2Fcontent%3Fid%3DPNZIdRZ-W28C%26printsec%3Dfrontcover%26img%3D1%26zoom%3D1%26source%3Dgbs_api

**Comment by guillaume-uH57J9** [comment]
Hi,

Images fail to load in Chromium 46 and Firefox 38.2.1. 
An HTTPS error is displayed When accessing images directly at https://inventaire.io/img/.. so I suspect this is related to this issue

Firefox error:
"Échec de la connexion sécurisée
La connexion avec inventaire.io a été interrompue pendant le chargement de la page.
* La page que vous essayez de consulter ne peut pas être affichée car l'authenticité des données reçues ne peut être vérifiée.
* Veuillez contacter les propriétaires du site web pour les informer de ce problème."

Chromium error:
"Page Web inaccessible
ERR_SPDY_PROTOCOL_ERROR"

**Comment by maxlath** [comment]
I just fixed a permission issue in nginx image caching, but it wasn't affecting image delivery (it was just preventing to use a cached version) so I'm not sure to see how those errors were related but I highly suspect they were: could you retry now to see if those errors persist?

**Comment by guillaume-uH57J9** [comment]
Images are back \o/

**Comment by maxlath** [comment]
woohoo \o/
