### ISSUE TITLE
Persona login last forever

### ISSUE THREAD

**Issue by MartinDelille** [inventaire/inventaire#16]
When trying to login to inventaire.io, I have the following message lasting forever:
![capture d ecran 2015-04-30 a 17 44 08](https://cloud.githubusercontent.com/assets/879889/7417607/7bf02d7e-ef67-11e4-8baf-a276743772d1.png)

**Comment by maxlath** [comment]
First, can you confirm that you were trying to connect using [Mozilla Persona](https://persona.org) on purpose? If you were just trying to create an account and were shown this screen without knowing what Persona is, you're not the first and it's a UI problem

**If you were trying to login with Mozilla Persona on purpose**: normally, when this screen is shown a popup should have open: you may need to change your popup settings for this page to see it (this is part of what makes Mozilla Persona problematic: relying on popups is a pain). There is no timeout on this loader as logging in with Persona may need different operations out of Inventaire's control, so it keeps spinning, waiting for Persona to make something happen. If the user already has an account and if the popup is visible, this spinner is OK I think; problems happen when 1 of those 2 conditions is missing. For both, better tips could be a good start

**Comment by MartinDelille** [comment]
Hi! I decided to create a Mozilla Persona account on purpose when discovering inventaire.io. I experienced this bug a first time and decided to make sure that my Persona account was ok directly on the project website (http://persona.org) which is ok now (martin@phonations.com).
Shouldn't the access work since I have an existing account?
I know I can create a regular account with email/password, but I wanted to try Persona at the same time and I decided to give you my feedback hoping this could help you.
I'm available for further information if needed!

**Comment by maxlath** [comment]
From what I can see, it seems that you had all good - a valid Persona account and a valid username - but that you did not validate the Persona popup then. Could you try to [signup with Persona](https://inventaire.io/signup/persona) again? It should redirect to this same loading page and open a Persona popup to let you bind your Persona and your Inventaire accounts.

**Comment by maxlath** [comment]
Sad news, Persona.org is closing :( #56 
All Persona signup/login options were removed from inventaire, [users who created an account with Persona are invited to create a password](https://inventaire.io/login/persona). The only good side in it being: Persona related issues can now be closed
