### ISSUE TITLE
Search results that match partial string search

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#163]
When search query is equal to "Jules ver", results display "Robert Ver" before "Jules Verne" 
Its happening because result match only on [spaced words](https://github.com/inventaire/inventaire/blob/52e405df4b43dfce9581a4e4dcfddecdc42619c4/server/controllers/entities/lib/common_query_body_builder.coffee#L7), instead of full query match.
It might be fixed by changing the "phrase_prefix" [term](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#type-phrase)

**Comment by maxlath** [comment]
the same request as in the comment above returns no result at all at the moment

**Comment by jum-s** [comment]
[Recent](https://github.com/inventaire/inventaire/pull/462) [changes](https://github.com/inventaire/inventaire/pull/478) [improved](https://github.com/inventaire/inventaire/pull/165) partial matches (as there is no `phrase_prefix` anymore). 
"Robert Ver" is not in the result anymore when searching "Jules Ver". And "Jules Vern" does return Q33977 (among Jules Vernon and others but that is not what this issue was reporting).
There is still space for improving partial match in general, but this may be done in a new issue
