### ISSUE TITLE
Work links to an edition that is not link to

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#168]
Sorry for the title. It seems complicated but it is not.

I don't know how that can happen, but there is a work [Fullmetal Alchemist, Vol. 1](https://inventaire.io/entity/inv:026a1856df319a2fe3c14c4db639cbcf) that displays an edition [Fullmetal Alchemist - Tome 2](https://inventaire.io/entity/isbn:9782351420188) that is not linked to it. Instead the edition has his own work [Fullmetal Alchemist - Tome 2](https://inventaire.io/entity/inv:b3f50d8f75205da720bf895399859a0d).  
The edition was linked to the work at the beginning but as it was incorrect, I created a new work for it and linked them together. I don't understand why the work *Vol.1* still displays *Tome 2* cover.

![screenshot-2018-4-18 fullmetal alchemist vol 1 - livre - inventaire](https://user-images.githubusercontent.com/823564/38914831-778f4906-42e1-11e8-8a30-93853d9bd427.png)

![screenshot-2018-4-18 fullmetal alchemist - tome 2 - inventaire](https://user-images.githubusercontent.com/823564/38914845-8cf91722-42e1-11e8-8981-bb190ee1d7e7.png)

![screenshot-2018-4-18 fullmetal alchemist - tome 2 - livre - inventaire](https://user-images.githubusercontent.com/823564/38914849-9119cbe4-42e1-11e8-869f-4521c7552c6e.png)

**Comment by maxlath** [comment]
so it looks like the client (probably during the new ISBN importer process) makes two requests for the same ISBN at about the same time, resulting in the same entity being scaffold in parallel, and thus the ISBN uniqueness test to fail: there are thus 2 entities with the same ISBN

you can see it from the API: [both `inv:b3f50d8f75205da720bf89539980bcb5` and `inv:b3f50d8f75205da720bf89539980cc85` redirect to `isbn:9782351420171`](https://inventaire.io/api/entities?action=by-uris&uris=inv:b3f50d8f75205da720bf89539980bcb5|inv:b3f50d8f75205da720bf89539980cc85)

I'm working on a PR to prevent such a situation from the server, before having a look at why the client requests the same data twice

**Comment by maxlath** [comment]
that should be solved now, please re-open if you see this case again, thanks!
