### ISSUE TITLE
Unable to add number of pages/volumes

### ISSUE THREAD

**Issue by simon-mettler** [inventaire/inventaire#172]
I'm unable to add the number of pages/volumes for any book. Seems to be a problem with the input field. `str.replace is not a function` appears as a error message (see screenshot).

![bildschirmfoto 2018-05-05 um 23 10 48](https://user-images.githubusercontent.com/25713681/39667626-dd2467b0-50ba-11e8-854d-31b18e0f73dd.png)

**Comment by maxlath** [comment]
hi, thank you for reporting this issue! The patch had been written https://github.com/inventaire/inventaire/commit/e8509b04440dce0c102025136ee743ad1df5e17e#diff-5243ef70564040d235eb142986e6e955 but I forgot to put it in prod ><
thanks again!
