### ISSUE TITLE
recover a shadow entity feature

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#181]
having the possibility to extend a Wikidata entity from Inventaire could be useful in some cases (#182).
We had that feature, but it was removed as it wasn't used defc9f7; it could just be recovered

**Comment by jum-s** [comment]
I have not set my mind upon this shadow item thing, seems handy to define customed props ok. 

But, if in a federated world, other people can define the same claim with another value. What if inventaire shadow claim is a doublon of the wikidata instance with a misspelled value ? 
How do we deal with claims that could fall in a conflict with womeone else definition ?
Constraining those shades/claims to a few specific properties seems the least we can do (`P18: image`) 
In those experimental days of federation understanding, opening the shadows possibility might look like a slipery way, we dont really know where it could lead yet.

**Comment by maxlath** [comment]
I agree, we should keep it to strictly necessary claims, like book covers that aren't supported by Wikidata, at least at first

**Comment by maxlath** [comment]
A comment I made today in the chat on the matter:

> The tight integration [with Wikidata] indeed comes at a real cost on our nerves, as any Wikidata contributor can decide that a work entity is actually an edition and break things on our side, any Wikidata oddity becomes our problem.
> I have been playing with ideas that I hope would make us more resilient, such as having an entity document locally in Inventaire database for each Wikidata entity of interest, with which it would have the equivalent of a sameAs relation. That local document could then have claims such as a type lock (a way of saying "this entity should be considered a work, whatever its P31 now says"), and data that can't be stored in Wikidata (the typical use case being a book cover)

**Comment by maxlath** [comment]
Instead of "shadow entity", I like the idea of an entity layer: several entity documents in several databases, identified as refering to the same concept ([`sameAs` relation](https://en.wikipedia.org/wiki/SameAs)), could be considered layers of the same entity. Such layers could overlap, or not. (In our case, I think they wouldn't need to)

**Comment by maxlath** [comment]
Coming back on this issue, it seems clear that having a local layer with only local properties would be a safe first implementation: there does not seem to be a need to override wikidata claims, so no need to handle having local and remove claims for the same wikidata property.

**Comment by maxlath** [comment]
Done in https://github.com/inventaire/inventaire/pull/753 :tada:
