### ISSUE TITLE
[new feature] entities lists

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#184]
Collection would be the name of list of entities (works, editions, articles, authors, series, subjects ? the exact restrictions are to be discussed or progressively extended, let's start with just works maybe) a user could build, with the possibility to add a piece of text per entry, that would be like a review bound to this collection. Reviews set on the entity independently from the collection could also be made visible from the client.

In a second time, those collections could also be owned collectively by a group.

![img_20180519_190309](https://user-images.githubusercontent.com/1596934/40360442-84ef4e02-5dc6-11e8-8494-d5fc3a6f57a9.jpg)
> Wikimedia Hackathon white board session with @jum-s 

Associated roadmap card https://trello.com/c/w1dxqgTb/123-books-lists

**Comment by maxlath** [comment]
what about giving the possibility to enriche a collection with some claims such as a subject (`wdt:P921`)? that could allow to link to the collection from the subject page

**Comment by maxlath** [comment]
then the question is how to link those books lists/collections to the inventories books, representing physical examplars. A solution could be to allow to sync operations on inventories books to their entities in a list: if I remove a book from my inventory, I could/should be offered to also remove its associated entity from the collections.

**Pros**
* bridges those different features together, allowing to solve the problem of "how to let users organize their inventory", the answer then being, that "bookshelves" are just subset of some collections a user happen to physically own

**Cons**
* might not be that straight forward to understand for the user?

**Comment by maxlath** [comment]
From a discussion with a bookshop worker: *"we call those « lists »"*

**Comment by jum-s** [comment]
Some services call it "collage", which can be of different category. The list below is adapted to inventaire data model :

- subject collage
- genre collage
- books collage: only for editions or works
- publisher collage: restricted to editions belonging to a single publisher
- personal personnel: any entity can be sticked together
 
All collage are publicly accessible: but i guess inventaire's visibility (shelf, item) could make sense 

Adding an entity to a collage can be open to everyone or closed to the creator.

Deleting entities added by another user is forbidden by default (except if it comes from the creator) but could be opened if the creator decides it

**Comment by jum-s** [comment]
My opinion is that opening collage edition to other users could be a powerful social feature

**Comment by jum-s** [comment]
conclusion of discussion between max and i, a week ago (expressed in pseudo-code representing db store)

current shelf implementation: 
```
shelf = { id }
item = { id, shelves: [ shelf.id ] }
```

implementation suggestion 1: simple yagni, maybe v1 ?
```
bibliography = {id, desc, entitiesUris: ["wd:Q535"], visibility, user}
```

implementation suggestion 2: more work (one more db to work with), but can support authored batch updates, maybe v2 ?
```
bibliography = { id, description, user, visibility }
listElement = { id, list: bibliography.id, detail }
```
