### ISSUE TITLE
Feature request: Names of authors clickable to find their works

### ISSUE THREAD

**Issue by frimelle** [inventaire/inventaire#20]
It would be a nice to have-
On the overview the author name could be clickable so it'd bring you to the search with the author's name to find more books by him/her.

**Comment by maxlath** [comment]
authors names are clickable when the book was found from Wikidata as it is already disambiguated (see [this book](https://inventaire.io/entity/wd:Q1396889) for instance ), but not when coming from Google Books (all books found by isbn or Editions in search) where author is just an ambiguous string for now

**Comment by frimelle** [comment]
Ah, yes, didn't really realize that, was actually more talking about this part: 

![authors-de](https://cloud.githubusercontent.com/assets/2714560/7859937/23c1bfca-0545-11e5-9ee7-b3ec05d59670.png)

Having here the authors clickable and thereby searchable would be a nice-to-have. (Kind of: I liked this book, let's see what else she/he wrote) But not sure if that's not completely confusing if it's only for the authors where the books are from Wikidata... 

But you perhaps could just forward the clicking on the author to the search page and pass the string there as if I had typed it? Not sure though.

**Comment by maxlath** [comment]
what is even more confusing is that those are "instances of books" = books users added to their inventory, which have their specific page as such; so currently, all what is above the avatar+username is just a big button toward the page of this book's instance, from which you can indeed go to the book's page or the author's page, when available. When not available, I keep your idea of searching from the author's name string! Unless confusing. we will see :)

**Comment by maxlath** [comment]
what is even more confusing is that those are "instances of books" = books users added to their inventory, which have their specific page as such; so currently, all what is above the avatar+username is just a big button toward the page of this book's instance, from which you can indeed go to the book's page or the author's page, when available. When not available, I keep your idea of searching from the author's name string! Unless confusing. we will see :)

**Comment by maxlath** [comment]
done! cf [inventaire-client commit aca6599](https://github.com/maxlath/inventaire-client/commit/aca6599d213e3e878a22637efdab61f3c117eed7)
Won't be visible on inventaire.io before a week or two though, we can wait for that to confirm that this issue should be closed.
