### ISSUE TITLE
GitHub does not detect the project's license

### ISSUE THREAD

**Issue by johnjago** [inventaire/inventaire#202]
On the project's [GitHub page](https://github.com/inventaire/inventaire), the license is not displayed in the commits/branches/releases/contributors bar, which means that GitHub cannot detect it.

This [help page](https://help.github.com/articles/licensing-a-repository/#detecting-a-license) explains why this might happen:
> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

This should be addressed because people might not find the project when [searching by license type](https://help.github.com/articles/licensing-a-repository/#searching-github-by-license-type).

Edit: Also true for the client repository.

**Comment by maxlath** [comment]
thanks!! it seems to be working now :)
