### ISSUE TITLE
Remove validate button

### ISSUE THREAD

**Issue by frimelle** [inventaire/inventaire#21]
To have to click on validate on the book's pages is inconsistent, since everything else is saved right after choosing the option. Thereby it's pretty confusing to have this one place where you have to validate your input. 
(At least moving the button to a more visible position right underneath the buttons would be cool, I tend to forget about it and wonder, why the books are not shown in my overview.)

**Comment by maxlath** [comment]
you are not the first I see forgetting to validate, this is definitely an issue. It could be solved by creating the book right at "add to my inventory" with default settings (visibility "private" and transaction "none" ? ), then updating it from the form

**Comment by frimelle** [comment]
Yes, that sounds actually perfect! Like exactly what I would expect!

**Comment by maxlath** [comment]
done! cf [inventaire-client commit c924956](https://github.com/maxlath/inventaire-client/commit/c924956ee880bad3e9581801a906994258fa7ed6)
can you check that it is the desired behaviour so that we can close the issue?

**Comment by frimelle** [comment]
Yes, perfect!
Only question left: Why is there still the validate button on the add to inventory page?
 I think it might be confusing to have the button because does it actually still do anything? I add the book as soon as I click on "add to my inventory"- so maybe get rid of the validate button there? 
(Same for the cancel button, since the book is added even when I click on cancel)

Maybe related: How do I remove a book now from my inventory?

**Comment by maxlath** [comment]
The validate button is needed to save the 'details' and 'notes' textarea, while the 'transaction' and 'listing' buttons are saved on click. This distinction might indeed be confusing. What about removing the Cancel and Validate buttons and add a little 'save' button under each textarea?

The cancel button is inherited from the previous item creation mechanism and was just doing nothing but redirecting to the home; which is fails to cancel with the new 'early creation' mechanism. It should indeed be removed.

**Comment by maxlath** [comment]
for the moment, deleting is done from the visibility menu: it was allowing to get access to it from the books columns layout (/inventory), without taking more place, but I guess a delete button is needed on book's page (/inventory/username/book:entity:uri)
