### ISSUE TITLE
Item notification doesn't bring you anywhere

### ISSUE THREAD

**Issue by frimelle** [inventaire/inventaire#22]
If you get an  new_comment_on_followed_item notification, you don't see what the notification is actually about and it just leads you to the Overview page without highlighting one book or something similar.
Also, the string should probably actually be a real sentence or something similar.

**Comment by maxlath** [comment]
I think this as been solved but isn't online yet: it's not very agile or anything but as I'm working on a big functionality (a books' requests manager \o/), I haven't put in production for a few weeks, thus the persistence of some identified bugs. I let this issue open for when the supposed fix will be online.
In details:
- `new_comment_on_followed_item` do have a translation in English (see [shortkey/en](https://github.com/maxlath/inventaire-client/blob/i18n/src/shortkey/en.json)). Other languages should default to the English version when no translation is available, so it should stop display as `new_comment_on_followed_item` soon
- clicking on the notification works in development: it redirects to the commented item's page. Let's wait for the new version to be in prod to confirm that

**Comment by maxlath** [comment]
it should be online now :)

**Comment by frimelle** [comment]
Looks good, everything works for me- except:
just saw that a very old notification looks very broken now;
![screenshot from 2015-06-23 18 25 07](https://cloud.githubusercontent.com/assets/2714560/8311385/16019bee-19d6-11e5-9e4c-f4b64a59aaa3.png)
(pretty pink anonymisation)
It's a month old, but I couldn't think of a reason, why this is still broken. Also, if I click on it, I get back to browse books.
(The new, working version not only does what it's supposed to do but looks also actually very nice though.)

**Comment by maxlath** [comment]
(I assume this isn't the case anymore and close the issue)
