### ISSUE TITLE
Language fallback for titles

### ISSUE THREAD

**Issue by frimelle** [inventaire/inventaire#23]
If there is no title in English, the title of the book is shown as the Wikidata entity id. It would be better, to have some kind of fallback to other languages if there is no label in English. 
Also it might be confusing for non-Wikidata people to understand what that id is about if there is no label at all. Perhaps there is a better solution for this? So display the fact that there is no label (and encouraging to edit it) rather then the entity id?

**Comment by maxlath** [comment]
yes, definitely

**Comment by maxlath** [comment]
I implemented a quick fix on entities missing title: when no entity label is found, the model will use the Wikipedia article title, when there is one. See [inventaire-client commit 10ca7f0](https://github.com/maxlath/inventaire-client/commit/10ca7f03f54bcda6de0c74d485dcb61fe45814cc#diff-0cb303c86fc683263bb6808c86abe410)

**Comment by maxlath** [comment]
We see less of those, right? Can we close this issue ?

**Comment by frimelle** [comment]
Yeah, seems to be a valid solution. Can be closed :+1: 
Thanks!

**Comment by maxlath** [comment]
:tada:

**Comment by maxlath** [comment]
this might have been closed too hastily unfortunatly:
ex: https://inventaire.io/entity/wd:Q1128109/Constanze_Kurz?lang=fr

**Comment by maxlath** [comment]
now its fixed ;) https://github.com/inventaire/inventaire-client/commit/16d94dd1d2d6ab8f2d5d0a9d0c4efca3679ac458
