### ISSUE TITLE
Include author name and Wikidata URI in exports

### ISSUE THREAD

**Issue by Abbe98** [inventaire/inventaire#28]

**Comment by maxlath** [comment]
Hey Albin, thank you for opening an issue!

For the moment, in data exports you get a field `entity`, which is a non-explicited prefixed URI: 
`"entity": "wd:Q2252893"`
You can easily re-build the Wikidata URI from it `https://www.wikidata.org/entity/Q2252893` but indeed it's neither clear nor standard.

Then authors data can then to be found from wikidata's data - in claims `P50` - but requires a bit of parsing. The data export could indeed provide a copy of it to make it easier to work with it, but would you like the author's name or her wikidata id? (here `Isaac Asimov` or `Q34981`)

I will be working on [Inventaire's API](https://github.com/inventaire/inventaire/wiki/API) in the coming months, that will be the occasion to make data exports clearer, any input on that - e.g. what particular endpoints you would like - are very welcome!

**Comment by Abbe98** [comment]
Because `entity` can have multiply sources such as only a isbn or inventaire URI, it's getting more complex and you has to use the Inventaire API, adding common data to the exports would make it less complex and eventually lower the amounts of request to the API.

**Comment by jum-s** [comment]
`items` export available in [labs](https://inventaire.io/settings/labs) now displays a snapshot that includes author names, work title, and work lang like this

```
      "snapshot": {
        "entity:title": "La zone du dehors",
        "entity:lang": "fr",
        "entity:authors": "Alain Damasio",
        "entity:image": "/ipfs/QmVqFBPC65cC1aUjNKSwkaAKorP7oSbk4RH4fUeAdEcXAh"
      }
```

For the moment snapshot display only those keys, in the future it could Wikidata URI for works.

**Comment by jum-s** [comment]
closing as CSV exports now includes snapshot which includes authors URLs and authors labels
