### ISSUE TITLE
document the API

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#29]

**Comment by Abbe98** [comment]
I'm currently working against the API and could do this in the near future.

**Comment by maxlath** [comment]
nice! I would love to see how you use it btw :)
Also your opinion on #31 is welcome!

**Comment by vindarel** [comment]
+1

**Comment by maxlath** [comment]
documentation started at https://github.com/inventaire/inventaire/wiki/API

**Comment by maxlath** [comment]
update: API documentation re-started at https://api.inventaire.io

**Comment by thewholelifetolearn** [comment]
For some operation, the terminal must be authenticated but there is no description on how to get authenticated. Would it be possible to add some information about it?

**Comment by thewholelifetolearn** [comment]
It is perhaps a stupid question but what is the difference between "items" and "entities"? I don't see it at first sight.

I would like to use the API to update/create books. It could be very helpful in case of long manga or comics series.  
For example, I would like to update all my series to take in account the new "ordinal" property. It would be much faster through the API then the website.

**Comment by maxlath** [comment]
@thewholelifetolearn I just added some documentation on [authentification](https://api.inventaire.io/#!/Auth/post_auth_action_login), and some [basic context to the differences between items and entities concepts](https://inventaire.github.io/entities-map/). Please continue to fire questions on anything unclear so that I can keep improving the documentation :)

**Comment by thewholelifetolearn** [comment]
I think there should be some documentation on properties.  
For example, I would like to update through the API the ordinal of several works of mangas. For that I will use the `update-claim` URL. But before I do, I need to know the property associated. The only way to know is by going through the code of Inventaire. In this case, the property is `wdt:P1545`

**Comment by maxlath** [comment]
yes. btw, your opinion on #98 is welcome

**Comment by maxlath** [comment]
closing this issue to open more specific ones: #152
