### ISSUE TITLE
implement an API-specific authentification mechanism

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#31]
What should be the API-specific authentification mechanism for private routes?
You can already query those routes passing your session cookies data, but that's not really nice. Implementing new authentifaction mechanisms should be pretty straightforward thank to passportjs.
Candidates:
- Basic Auth
- Oauth

any better options?

**Comment by AmauryVanEspen** [comment]
Hi,

what would you think about cross fertilization with ABES / SUDOC ? (like World Cat)
http://www.slideshare.net/jsicot/utiliser-les-apiwebservices
http://www.sudoc.abes.fr/
http://www.abes.fr/

Best

Amaury

**Comment by maxlath** [comment]
update: we got Basic Auth! a1edad2

**Comment by maxlath** [comment]
OAuth got its own issue: #84
