### ISSUE TITLE
import should try to match existing entities before creating duplicates

### ISSUE THREAD

**Issue by Alamantus** [inventaire/inventaire#311]
When I ran an import of my GoodReads data (very impressive, by the way!), I noticed that _some_ of the books correctly connected to existing entities (whether Author or Works/Editions) but others with the exact same names ended up creating duplicate records. Specifically, with Warbreaker parts 1–3 by Brandon Sanderson, Inventaire imported Part 1 and Part 3 correctly with the pre-existing author entity attached, but Part 2, even though it had the exact same wording, created a duplicate Brandon Sanderson author entity.

I understand that this behavior is to take care of cases where the name of an entity is a homophone/work with the same name, but I would argue that Inventaire should always search for pre-existing entities for matching Work/Edition and Author names and assume records with identical names are correct rather than erring on the possibility that the exact matches are homonyms (especially with GoodReads imports!). If the author or work actually _is_ a homonym, it's easy enough to create a new author record in work, but in (I believe) the majority of cases, the author will be the same as the one that already exists in Inventaire.

I believe that erring on the possibility that an import is referring to pre-existing works, editions, or authors with the exact title rather than creating duplicates will help reduce the amount of merging and deletion required by admins moving into the future as more people import and expand the database, and the sooner the change is applied, the easier that cleanup process will become!

**Comment by maxlath** [comment]
what I take from it:
* see what failed in the Warbreaker part 2 resolution, given it worked for part 1 and 3
* data imported in bulk should use resolved entities within the bulk to resolve homonyms

**Comment by maxlath** [comment]
Since https://github.com/inventaire/inventaire-client/pull/212 the importer is using the `resolve` endpoint, which should in most cases be able to this work of matching with existing entities, so I will close this issue for now, but please reopen if you see entities that should definitely not have been created
