### ISSUE TITLE
extend whitelisted properties to more authority control IDs

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#328]
Inventaire already have some [authority identifiers](https://github.com/inventaire/inventaire/blob/master/server/controllers/entities/lib/properties/properties_per_type.coffee#L16). But its restricted to some arbitrary narrow list.
The nice [prop explorer tool](https://tools.wmflabs.org/prop-explorer/) provides a list of those identifiers called "Wikidata property for authority control for works" . 
Here is the list of props not in inventaire yet that describe more than 500 entities :

```
463k entities : "P268" # identifiant Bibliothèque nationale de France
90k entities :  "P243" # identifiant OCLC
16k entities : "P1144" # LoC éditions
16k entities : "P1274" # identifiant ISFDB d'un titre
10k entities : "P1844" # identifiant HathiTrust
5k entities : "P3155" # identifiant Projet Runeberg d'un livre
4k entities : "P1182" # identifiant LIBRIS
3k entities : "P675" # identifiant Google Livres
3k entities : "P5571" # identifiant NooSFere d'un livre
1k entities : "P1292" # identifiant DNB (éditions)
729 entities : "P4258" # identifiant Gallica
709 entities : "P1143" # identifiant BN (Argentine)
654 entities : "P3184" # identifiant de la bibliographie nationale tchèque
```

Advantages:

- More identifiers may help users to understand more what inventaire displays.
- Starting with this whitelisting could also in future provide to the users the capacity to edit more entities  external ID easily.
- Some parts of the app uses some external sources to disambiguate entities ([tasks](https://github.com/inventaire/inventaire/blob/master/server/controllers/entities/lib/get_occurrences_from_external_sources.coffee)) and could use sourced entities to help even more disambiguation.
- More generally its about accepting, using and editing more linked data which cannot be a bad thing right?

**Comment by maxlath** [comment]
@jum-s can this be closed now that #329 was merged?
