### ISSUE TITLE
small language issues

### ISSUE THREAD

**Issue by fkooman** [inventaire/inventaire#33]
"Feedbacks" -> "Feedback"
"Send a feedback" -> "Send feedback"

**Comment by fkooman** [comment]
Not entirely fixed ;-) You forgot the "Send a feedback"...

Wheel -> Discussions -> Send a feedback

Maybe "Discussions" should also be "Discussion"... not sure about that one :)

**Comment by maxlath** [comment]
done! [`f1ee818`](https://github.com/inventaire/inventaire-client/commit/f1ee8180c88c6992034a75ea766baa59a1234435)
