### ISSUE TITLE
wrong API route or http verb when loging in

### ISSUE THREAD

**Issue by roptat** [inventaire/inventaire#343]
Hi,

when loging in the website I get this JSON document:

```json
{"status":400,
 "status_verbose":"wrong API route or http verb",
 "context":{
   "verb":"GET",
   "url":"/api/submit"
  }
}
```

I'm not redirected to a webpage, but I'm correctly logged in after I manually go to the home page of inventaire.io.

**Comment by maxlath** [comment]
Hi,
For some reason, you are doing a GET instead of a POST. Which browser version are you using?

**Comment by roptat** [comment]
I'm using IceCat 68.3.0esr (like Firefox esr)

**Comment by maxlath** [comment]
it happens to be the only form submit of the whole app (used to trigger browsers password managers). [It is set to `method=post`](https://github.com/inventaire/inventaire-client/blob/665f2188/app/modules/user/views/templates/browser_login_form_attributes.hbs#L1), but your browser seems to ignore it :/

**Comment by roptat** [comment]
Looking at the network logs of my browser, I first do a POST request to https://inventaire.io/api/submit, which is a 302 with a location header set to https://inventaire.io/api/submit, which makes my browser request it again, using the GET method.

**Comment by maxlath** [comment]
hehe! so new clue from the logs: it seems that your browser sent a `https://inventaire.io/api/submit` as `referer`, which then, [in absence of an explicit redirection is used to trigger the redirection from the where the user was](https://github.com/inventaire/inventaire/blob/d413c908/server/controllers/auth/fake_submit.js#L22). I don't think this behaviour is needed anymore so the easiest would be to simply get rid of it

**Comment by maxlath** [comment]
I restarted the server with bc49d6a3, can you test again?

**Comment by roptat** [comment]
It works, thanks! That weird referrer is probably part of an anti-tracking feature. I guess I'll try disabling it next time I see something obviously broken :D
