### ISSUE TITLE
Items list

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#344]
bookshelf/bookshelves would be the name of a collection of items (different from [collections](https://github.com/inventaire/inventaire/issues/184) as entities list.)

An example of response in pseudo JSON on the endpoint `GET "/api/bookshelves?ids=bookshelfId1|bookshelfId2` :

```
bookshelves: { 
  bookshelfId: {
    owners: [ userId, groupId ],
    listing: 'public',
    name: 'whishlist',
    description: 'foo bar ',
  }
}
```
to ease client understanding (`if(item.bookshelves)` ) items would reference to whose bookshelves they belong : 
```
item: {
  entity: entityUri,
  listing: 'private',
  transaction: 'inventorying',
  owner: userId,
  bookshelves: [ bookshelfId1, bookshelfId2 ]
}
```
specs : 

groups can have a bookshelf
only owners can update a bookshelf
adding an entity to a bookshelf would create the item
delete a bookshelf would delete all items in it too

questions : 

- can bookshelves have several owners (allowing to share a common bookshelf) or does bookshelves solely rely on groups permission ?
- is the current feature `my inventory` becoming a default bookshelf ? would involve too much modification of the client side ? 
- what happens when items owner and bookshelves owner appears to be different ?

**Comment by jum-s** [comment]
related to https://trello.com/c/w1dxqgTb/123-books-lists

**Comment by jum-s** [comment]
default shelves could be set up at account creation. [BoardGameGeek](https://boardgamegeek.com/boardgame/202670/ticket-ride-rails-sails/stats) seem to have a fixed number of "collections" which could help defining inventaire shelves : 

![Sélection_003](https://user-images.githubusercontent.com/5363918/71536780-144a1580-290b-11ea-94e6-760f953ffd09.jpg)

visibility of an item in inventaire already takes care of the "for trade" collection on BGC, but own and wishlist could be two default shelves.

**Comment by jum-s** [comment]
Current features:
 - CRUD `name`(`title`?), `description` and `listing` (visilbility private/groups/public) keys
 - add shelves ids to items
 - optionally delete all items when deleting a shelf
 -

**Comment by maxlath** [comment]
done in #371 and https://github.com/inventaire/inventaire-client/pull/224 :tada:
