### ISSUE TITLE
Error during npm install on Raspberry/Debian10

### ISSUE THREAD

**Issue by frederic-leger-FR** [inventaire/inventaire#345]
Hi,
I'm trying to install inventaire on Raspberry PI4 with Debian Duster (based on Void Linux install).
Libraries and tools installed with nvm 8.16.2, npm v6.4.1.
git clone https://github.com/inventaire/inventaire.git <= Last inventaire.io release.
An error occur after "npm install" :

> /home/inventaire/.node-gyp/10.15.2/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:66:61:   required from here
/home/inventaire/.node-gyp/10.15.2/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [leveldown.target.mk:119: Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/opt/inventaire.io/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.75-v8+
gyp ERR! command "/usr/bin/node" "/opt/nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/inventaire.io/node_modules/leveldown
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/inventaire/.npm/_logs/2019-12-14T16_51_33_420Z-debug.log

[2019-12-14T16_51_33_420Z-debug.log](https://github.com/inventaire/inventaire/files/3964080/2019-12-14T16_51_33_420Z-debug.log)

**Comment by maxlath** [comment]
which version of Node are you using? we are currently locked on Node `<= v8` until we upgrade `level-party`, which depends on an old version of `leveldown` that doesn't work in more recent versions of Node. Fortunately, an updated version of level-party was recently published so that kind of issue should hopefully be solved soon

**Comment by jum-s** [comment]
Depending your usage, you could also alternatively use the docker
install https://github.com/inventaire/docker-inventaire. Its not
recommended for production purposes, but for a local instance, it can
ease a lot de deployment process.

It can also help the native deployment process, for exeample you can see
a confirmation of max precedent message here
https://github.com/inventaire/docker-inventaire/blob/master/Dockerfile.inventaire#L1

**Comment by innovTech** [comment]
> which version of Node are you using? we are currently locked on Node `<= v8` until we upgrade `level-party`, which depends on an old version of `leveldown` that doesn't work in more recent versions of Node. Fortunately, an updated version of level-party was recently published so that kind of issue should hopefully be solved soon

Sorry, I have the default Debian node release :  nodejs 10.15.2~dfsg-2+rpi1. I will install older version.

**Comment by innovTech** [comment]
> Depending your usage, you could also alternatively use the docker ...
I do not use docker for this server, but I try to create manual install with documentation for generic linux server. Many thanks.

**Comment by maxlath** [comment]
Closing as likely obsolete, do re-open if still meaningful
