### ISSUE TITLE
Books not loaded in inventory(entity_not_found)

### ISSUE THREAD

**Issue by Abbe98** [inventaire/inventaire#35]
Books does no longer load at `https://inventaire.io/inventory` showing "no item here...".

JS error `entity_not_found` trigged at `loggers.coffee:16`:

```
0: "Error: entity_not_found"
1: " at Object.t.exports.i.new (https://inventaire.io/public/javascripts/app.js?f48ff96:1:15911)"
2: " at https://inventaire.io/public/javascripts/app.js?f48ff96:2:30590"
3: " at r (https://inventaire.io/public/javascripts/vendor.js?f48ff96:8:28701)"
4: " at e.exports.e._settlePromiseFromHandler (https://inventaire.io/public/javascripts/vendor.js?f48ff96:7:25964)"
5: " at e.exports.e._settlePromiseAt (https://inventaire.io/public/javascripts/vendor.js?f48ff96:7:28560)"
6: " at e.exports.e._settlePromises (https://inventaire.io/public/javascripts/vendor.js?f48ff96:7:30461)"
7: " at r._drainQueue (https://inventaire.io/public/javascripts/vendor.js?f48ff96:6:26440)"
8: " at r._drainQueues (https://inventaire.io/public/javascripts/vendor.js?f48ff96:6:26501)"
9: " at MutationObserver.drainQueues (https://inventaire.io/public/javascripts/vendor.js?f48ff96:6:25225)"
```

Try seeing if errors are thrown visiting my inventory from another account([inventory/abbe](https://inventaire.io/inventory/abbe)), other users inventories seams to work fine for me...

**Comment by Abbe98** [comment]
The direct URL to my profile seams to work fine even for me, still without appending abbe it breaks.

**Comment by maxlath** [comment]
I'm inspecting the `entity_not_found` which is poping up everywhere, but without visible "damages" usually. The "no item here..." might actually not be a bug, rather a change in the default inventory filter: while developping groups, it was simpler to show friends items only by default, thus not including your own books; thus, if you have no contact yet or if they have no book, seeing "no item here..." is normal. That said, it is a bit sad to have this empty inventory by default while your inventory can be full of resources: moving back to a default filter "friends+user" could totally make sense.

**Comment by Abbe98** [comment]
Friends+user would be a better solution and friendly for new users.  Another solution would be to check if the user has any friends and iaf so is the case show friends books otherwise show the users books...

**Comment by maxlath** [comment]
this issue was solved by the new entities system: creating an item now requires having an existing associated work or edition entity (and progressively pushing for creating items from editions entities only), so `entity_not_found` errors shouldn't occur anymore
