### ISSUE TITLE
don't use ssh to clone repos in scripts (use https)

### ISSUE THREAD

**Issue by elf-pavlik** [inventaire/inventaire#36]
* https://github.com/inventaire/inventaire/blob/master/scripts/install-client#L1
* https://github.com/inventaire/inventaire/blob/master/scripts/postinstall#L6

**Comment by maxlath** [comment]
isn't it a question of preferences? I do prefer to use ssh as then I don't have to enter my password again while https would ask for it everytimes I try to push something

**Comment by elf-pavlik** [comment]
I don't think anyone else than you will push to this branch, and you can easily change git remote from http to ssh in your local clone... Do you use ssh key not protected with a pass password?

`git remote set-url origin git@github.com:maxlath/inventaire-client.git`
http://git-scm.com/docs/git-remote.html

**Comment by frimelle** [comment]
I agree.
There shouldn't be something that hinders any one on installing it like a personalization in the ssh.
