### ISSUE TITLE
Unauthorized admin API access

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#380]
I'm going through my inventaire to update my items, and particularly the authors. I realized that it is now possible to merge entities. I find that great. But when I want to merge 2 entities I get this error message: "Unauthorized admin api access".

![image](https://user-images.githubusercontent.com/823564/79055982-f7371980-7c51-11ea-99ad-1631ffe46129.png)

If I'm not authorized to do this action as I don't have enough privilege to do so, then the possibility to merge shouldn't be displayed at all.

**Comment by maxlath** [comment]
oups! that's a mistake on the client side: that should normally be display only for admins indeed.

**Comment by maxlath** [comment]
fixed by https://github.com/inventaire/inventaire-client/commit/614e389
