### ISSUE TITLE
Is authentification with API working?

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#382]
I would like to use the API to update entities in a batch but I can get the authentication to work. Is the documentation up to date? Is the API working?

I tried to modify with the API doc, but it doesn't function too.

I went through the source code but I didn't understand it :'(

**Comment by maxlath** [comment]
oups, it seems [the API documentation was missing the `/api` prefix in the endpoints](https://github.com/inventaire/inventaire-api/commit/6960728) (that would require further investigation to get when it started ignoring that `basePath` variable). In general, the documentation is not super up to date I'm afraid :( so feel welcome to ask questions if something doesn't work or is missing

for your use-case, the recommended workflow would be:
* get your session cookies `express:sess` and `express:sess.sig`, which can be done
  * either by copying it from the [network monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) in your browser
  * or from the API: 
```sh
curl -X POST "https://inventaire.io/api/auth?action=login" --data '{"username":"yourusername","password":"yourpassword"}
```
, the session cookies will be in the response headers
* make requests authentified with those session cookies, example to add a subject to a work:
```sh
curl -X PUT "https://inventaire.io/api/entities?action=update-claim" --data {"uri":"inv:f14f552f33dad73d34b565dc38fbb562","property":"wdt:P921", "new-value":"wd:Q2005"}
```

**Comment by jum-s** [comment]
if you are fine with leaving your password in the command line you can also go with a password authentication  : 
```
curl -H 'Content-Type:application/json' -H 'Accept: application/json' -XPOST -u username:password "https://inventaire.io/api/entities?action=delete-by-uris" -d '{"uris":"inv:9f88ec825979fd6543e08ae0fe270ea7"}'
```

**Comment by maxlath** [comment]
ouh yes, I forgot to mention the possibility to use BasicAuth. It's also an option, and it's simpler, but it makes slower requests than with cookies as the password will have to be checked each times (and that process is slow on purpose): that would make batch edits much slower

**Comment by jum-s** [comment]
oups i didnt get its for a batch update

**Comment by thewholelifetolearn** [comment]
Ok. I got it to work with Rester (a Firefox extension). I will try to do a script to update claims in a batch perhaps this evening.

The **/api** prefix wasn't the problem but that the data submitted must be in **json** form. It is written nowhere.
The error messages should be clearer. When I wanted to update a claim, I got a message that the action "update-claim" didn't exist. I realized then that I was in POST method and not PUT. The error message should suggest such things.

**Comment by thewholelifetolearn** [comment]
So I got it to work. The API server is functioning well. I had to adjust the curl commands. A cookie is needed to maintain the session:
**Authenticate:**
```bash
curl --silent -L --request POST https://inventaire.io/api/auth?action=login \
	    --cookie-jar cookie.txt \
		--header 'Content-Type: application/json' \
		--data "{
		"username": "foo",
		"password": "bar"
	}"
```
**Update:**
```bash
curl --silent --request PUT 'https://inventaire.io/api/entities?action=update-claim ' \
	        --cookie cookie.txt \
            --header 'Content-Type: application/json' \
            --data '{
                "uri": 'inv:71b4f804c097431886e9ea2d3433e602',
                "property": "wdt:P179",
                "old-value": "inv:71b4f804c097431886e9ea2d343e3759", 
                "new-value": "wd:Q718449"
            }'
```

Have a look at my gist for the entire process: https://gist.github.com/thewholelifetolearn/2dbce82f6a6b1619ba40b52bf696dfc6

**Comment by jum-s** [comment]
nice ! 
I played with it a bit on a local environment, here is a modified version
https://gist.github.com/jum-s/820d250803a1a4caf045e03473f36c34
The double/single quote JSON interpolation is quite a hassle, this script is using `printf`, so it can be run from the cli

**Comment by thewholelifetolearn** [comment]
Thank you for your version. I improved my script by taking in account what you suggested.

**Comment by thewholelifetolearn** [comment]
> oups, it seems [the API documentation was missing the `/api` prefix in the endpoints](https://github.com/inventaire/inventaire-api/commit/6960728) (that would require further investigation to get when it started ignoring that `basePath` variable). 

The base path is now written twice: `curl -X GET --header 'Accept: application/json' 'https://inventaire.io/api/api/entities?action=by-uris&uris=wd%3AQ3203603%7Cisbn%3A9782290349229%7Cinv%3Ad59e3e64f92c6340fbb10c5dcf437d86&refresh=false'`. You have to revert 696072867ae150a4aa0ff754fcdffbb00216d25b commit.

**Comment by maxlath** [comment]
reverted 87bfadc9
