### ISSUE TITLE
out-dated work language property: P364 needs to be replaced by P407

### ISSUE THREAD

**Issue by exilexi** [inventaire/inventaire#393]
We are currently tracking the language under P364, which is only for video content. We should use P407, which is more general and applies to text content.

**Comment by maxlath** [comment]
yes

For context, [when we added it](https://github.com/inventaire/inventaire/commit/a335077), the property was labeled "original language of work"; it was then [repurposed* to accomodate the WikiProject Movie](https://www.wikidata.org/wiki/Property_talk:P364#Decision_is_to_delete;_mark_as_deprecated).

*which should never be done in my opinion

**Comment by maxlath** [comment]
fixed! \o/

## Code
* server: https://github.com/inventaire/inventaire/commit/4c37f934
* client: https://github.com/inventaire/inventaire-client/commit/2eef114
* i18n: https://github.com/inventaire/inventaire-i18n/commit/a5dcdc1

## Fixed data
* Wikidata:
  * [moved books P364 to P407](https://tools.wmflabs.org/editgroups/b/wikibase-cli/c65037fcc3228/)
  * [remove P364 value from books that already have a P407](# https://tools.wmflabs.org/editgroups/b/wikibase-cli/479fcb0f61f3a/)
* Inventaire: [rewrote data directly in the database](https://github.com/inventaire/inventaire/blob/master/docs/data_transformation.md#by-modifying-the-document-as-text)

**Comment by exilexi** [comment]
Nice, thanks!

**Comment by maxlath** [comment]
Fixed series data:
* Wikidata:
  * moved books P364 to P407: [batch 1](https://editgroups.toolforge.org/b/wikibase-cli/dd3d9cbead855/) [batch 2](https://editgroups.toolforge.org/b/wikibase-cli/91f3908f8f1ec/)
  * [remove P364 value from books that already have a P407](https://editgroups.toolforge.org/b/wikibase-cli/632ac830f0c9f/)
* Inventaire: [rewrote data directly in the database](https://github.com/inventaire/inventaire/blob/master/docs/data_transformation.md#by-modifying-the-document-as-text)
