### ISSUE TITLE
bug: a card is modified after creation by old isbn

### ISSUE THREAD

**Issue by vindarel** [inventaire/inventaire#40]
I tried Inventaire with these steps:
- I looked for an isbn (a french book). Didn't find results, so
- I created the card manually, but I registered another book. One without isbn. I'm pretty pretty pretty sure I deleted the isbn from its field (it was pre-filled).
- all seems ok
- I come back, and in my inventory I can see the right title but associated with the author of the first isbn search. When I click on that book, I have all the information from my first isbn search.

So at least 3 bugs:
- my card is modified somehow
- mismatch between the title and the author
- mismatch with the title on the Inventory page and the details page.

and one question:
- seems strange that my isbn search didn't give any results but that my card is modified… will try to re-create the bug.

**Comment by maxlath** [comment]
I couldn't find the events in the logs but I think I spotted were the problem could have come from: the entity creation form was not updating the entity model when the input value was an empty string, thus a deleted value wasn't updating the model.
see commit [1199d88](https://github.com/inventaire/inventaire-client/commit/1199d88902794b8f4c450c164591b57e172f28ba] on client repo
The fix should be online this afternoon

**Comment by maxlath** [comment]
(I assume this was the right fix and close the issue)
