### ISSUE TITLE
Change social cards metadata

### ISSUE THREAD

**Issue by exilexi** [inventaire/inventaire#402]
If I share a link to my profile on social media, the preview image is my profile pic, cropped and unreasonably large.

Inventaire preview:
![image](https://user-images.githubusercontent.com/8208894/83350345-cdd66800-a33b-11ea-8150-a8a3e3dc5740.png)

I'd love it if instead, we could either:
* generate a small preview image composed from the covers of the first 4-5 books in the inventory
* have a small image with a text presentation, like Goodreads does

Goodreads preview, for reference:
![image](https://user-images.githubusercontent.com/8208894/83350402-26a60080-a33c-11ea-9e92-9a1991efef40.png)

**Comment by maxlath** [comment]
done in commits:
https://github.com/inventaire/inventaire-client/commit/18f91615
https://github.com/inventaire/inventaire-client/commit/5e8a629f
https://github.com/inventaire/inventaire-client/commit/f291ad7d

new facebook card:
![fb_card](https://user-images.githubusercontent.com/1596934/83634544-0330bf00-a5a3-11ea-87e8-650a266375f9.png)

new twitter card:
![twitter_card](https://user-images.githubusercontent.com/1596934/83634546-0461ec00-a5a3-11ea-90ff-346ae0eeb838.png)

anything missing?

**Comment by exilexi** [comment]
That's much better, thank you!
