### ISSUE TITLE
add the possibility to revert an entity edit/restore an entity to a previous version

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#408]
We lack those basic wiki actions.

**Comment by jum-s** [comment]
Although i understand its a core feature of mediawiki, it looks like [trello does not have any either](https://trello.com/c/WqdwaPUW/13-tagging-system-categories). 
By this i mean that some "big" plateforms also lacks this feature (or that trello sucks, your pick)

**Comment by maxlath** [comment]
done in #419
