### ISSUE TITLE
(question) Why CouchDB ? I thought we should never use it

### ISSUE THREAD

**Issue by vindarel** [inventaire/inventaire#41]
I never worked with CouchDB or Mongo or other NoSQL.
I read a great article explaining why we shouldn't use them *when we construct relational data*, like I think is the case in Inventaire, and when dealing-searching books in general.
http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/

So, just for my information really, do you think it is really a good choice and why ? Thanks very much for the explanations :)

**Comment by maxlath** [comment]
the honest answer is that I'm a young developer and after a contest last year implying doing the prototype of a [Cozy](https://cozy.io) app, which required learning CouchDB, I just started Inventaire with the technologies I just learned.
And now I'm quite happy with that:
- the schema flexibility made prototyping rather easy
- I learned HTTP and not some non-standard protocole (compared to Mongo, I wouldn't mind have a better knowledge in SQL)
- there is no need for now, but master-master replication feels like future-proof, (cf [Spotify issues with PostgresQL bottleneck](https://labs.spotify.com/2015/06/23/user-database-switch/))
- [PouchDB](http://pouchdb.com) opens possibilities of data syndication worth exploring
- Last but not least, working with JSON models from the database to the front-end model feels right in terms of consistency
