### ISSUE TITLE
Allow passwords longer than 60 characters.

### ISSUE THREAD

**Issue by acagastya** [inventaire/inventaire#411]
Hi.  When I tried creating an account today, I got this issue.
<img width="661" alt="Screenshot 2020-08-08 at 14 29 59" src="https://user-images.githubusercontent.com/5466083/89706474-a4f9d100-d983-11ea-9d5e-bb557fc0d299.png">

Is there a reason to set this limit?  Aren't passwords hashed and stored?  If it is not a problem, can you please remove the limit?

**Comment by maxlath** [comment]
> Is there a reason to set this limit?
I can't recall the reasoning, probably that it seemed like a good value back then

> Aren't passwords hashed and stored?
yes they are, and the resulting hash length indeed isn't affected by the input length

> If it is not a problem, can you please remove the limit?
I increased the limit to 5000 characters: an arbitrary limit above which login requests would be unnecessarily "expensive". But if there is a use-case for a higher limit, I could be open to increase or remove it

**Comment by acagastya** [comment]
Thank you, @maxlath.  
However, why is there an upperlimit on password length?
