### ISSUE TITLE
Integration with The Storygraph

### ISSUE THREAD

**Issue by exilexi** [inventaire/inventaire#413]
I also suggested that to Nadia, who runs The Storygraph. The Storygraph is a platform that serves as an independent alternative to Goodreads; it supports reading advancement, to-read lists, reading challenges, some basic community features such as reviews, and a great recommendations algorithm (only for books in English as of now). On books, you can mark books as owned: I’d love to be able to link accounts so that my Inventaire books show up as owned in the Storygraph, and my to-read books are highlighted in Inventaire, among other possible collaboration types.

**Comment by maxlath** [comment]
I don't know for linking accounts, but linking bibliographic data could be possible, as they seem to have stable identifiers which OpenLibrary started referencing ([example](https://openlibrary.org/authors/OL4996526A.json)), and there is a freshly created [The StoryGraph author ID (P12430)](https://www.wikidata.org/wiki/Property:P12430)
