### ISSUE TITLE
check subclasses tree to type entities

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#414]
## problem
ex: if someone creates a subclass of a literary genre such as [Q3739522](https://www.wikidata.org/wiki/Q3739522), and uses it as a genre (wdt:P136) value, it will reject the claim due to the "invalid entity type": the server is incapable to check the subclass tree to find that inherited type

## proposed solution 1
make get_entity_type an async function that can check inheritance

Pros:
- no need to add all the smallest types aliases to the [wikidata type aliases list](https://github.com/inventaire/inventaire/blob/master/server/lib/wikidata/aliases.js)

Cons:
- higher performance cost, due to those async operations, but that should be mostly limited to Wikidata entities

## proposed solution 2
generate [wikidata type aliases](https://github.com/inventaire/inventaire/blob/master/server/lib/wikidata/aliases.js) from a SPARQL query, periodically refreshed to integrate

Pros:
- no need for async just-in-time checks like in the previous solution

Cons:
- needs to be updated from time to time
- might need some special rules to work around things that could be considered subclasses of several types

**Comment by jum-s** [comment]
[`get_entity_type`](https://github.com/inventaire/inventaire/search?q=get_entity_type&unscoped_q=get_entity_type) seems to be used when an entity creation or update happen. Those requests will be triggered only in case of unknown (non-aliased) P31 or P279 value, which greatly reduces this query occurrences to find subtypes.

Would the second proposition mean to store the subclass tree somewhere (ie. in the aliases list) ? If yes, then it doesnt look trivial as, for example, the number of subclasses for a big entity like [written work](https://query.wikidata.org/#SELECT%20%3Fs%20%3Flabel%20%7B%0A%20%20%3Fs%20wdt%3AP279%2a%20wd%3AQ47461344%20.%0A%20%20%3Fs%20rdfs%3Alabel%20%3Flabel%20filter%20%28lang%28%3Flabel%29%20%3D%20%22en%22%29.%0A%20%7D)(* operator :heart: ) is *quite* high. 

I dont know if there is a way to query all the superclasses of an entity instead.

**Comment by maxlath** [comment]
Something to have in mind: when indexing entities in Elasticsearch from the Wikidata dump, we currently [start by doing a `grep` based on the Wikidata P31 aliases](https://github.com/inventaire/inventaire/blob/aca7dbe/scripts/indexation/wikidata/load_from_dump.sh) to get a workable dump subset. That subset is then passed to the [indexation load script](https://github.com/inventaire/inventaire/blob/aca7dbe/scripts/indexation/load.js), which will use the [`entity` formatter](https://github.com/inventaire/inventaire/blob/aca7dbe/server/db/elasticsearch/formatters/entity.js), which in turn calls the `getEntityType` function. If we were to go with the propositon 1, we could not get a dump subset based on wikidata P31 aliases, as those aliases would not be complete, so we would need to process all wikidata entities and check if there P31 values can resolve to something of interest. That seems frighteningly long.

I would thus prefer to make a variation of proposition 2: keep a list of known valid P31 aliases, and use SPARQL requests to complete that list, while excluding known problematic cases. As a pseudo query: select all recursive subclasses of the following entities (ex: all the `works` P31 aliases), excluding all entities that are in one of the other aliases lists, or are a subclass of such an entity. Known special cases could be kept hard-coded.
