### ISSUE TITLE
stop rejecting valid email addresses

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#42]
an address such as `this.email+isvalid@example.org` might be exotic but is a perfectly valid email, currently rejected by the email-validation service

**Comment by hugoroy** [comment]
I just experienced this, so this is either not deployed or not completely fixed :-)

**Comment by maxlath** [comment]
I can't find where you got an "invalid email" error, could you give me more details, either here or by email at hello@inventaire.io?

**Comment by hugoroy** [comment]
1. Email «Bienvenue sur Inventaire.io !! Voici le lien pour confirmer votre adresse email»
2. https://inventaire.io/api/auth/public/token?action=validation-email&email=hugo+inventaire.io@XXXXXXX&token=XXXXXXXXXXX
3. ![capture d ecran de 2015-09-14 10-40-54](https://cloud.githubusercontent.com/assets/1629771/9845684/2c65f51e-5acd-11e5-82ca-13c5f2b669ab.png)
4. «Envoyer un nouveau mail de confirmation»
5. Retourner à l'étape 1

**Comment by maxlath** [comment]
probably an issue with the email not being escaped in the post-inscription email validation process, I will have a look at that. Thank you for reporting!

**Comment by maxlath** [comment]
the fix is online, could you try to request a new confirmation email?

**Comment by hugoroy** [comment]
Same issue.



-- 
Hugo Roy – Free Software Foundation Europe https://fsfe.org/about/roy
 
Please use cryptography for email: see https://emailselfdefense.fsf.org/en/
Merci d’utiliser la cryptographie pour l’email : voir https://emailselfdefense.fsf.org/fr/

**Comment by maxlath** [comment]
I didn't reboot the server properly, now it should work

**Comment by hugoroy** [comment]
↪ 2015-09-14 Mon 11:36, maxlath <notifications@github.com>:
> I didn't reboot the server properly, now it should work

It worked. Now the email is fully escaped (the plus and the arobase)
in the validation email.



-- 
Hugo Roy – Free Software Foundation Europe https://fsfe.org/about/roy
 
Please use cryptography for email: see https://emailselfdefense.fsf.org/en/
Merci d’utiliser la cryptographie pour l’email : voir https://emailselfdefense.fsf.org/fr/

**Comment by maxlath** [comment]
thanks!
