### ISSUE TITLE
allow to get a list of items that are in no shelves

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#430]
that would allow the client
* to display a "no shelf" shelf: addressed by #445
* to suggest those books first in the "add books to shelf" menu

**Comment by maxlath** [comment]
the server side part being done #445, remains the client side: I would suggest to wait for the Svelte refactor of the inventory browser, as adding a "no shelf" element in a list in Backbone.Marionette requires some ugly hack (namely adding a pseudo model to the collection), while that should be much easier in Svelte

**Comment by jum-s** [comment]
client side is done with svelte rewrite
