### ISSUE TITLE
Shelf edition requires a description

### ISSUE THREAD

**Issue by Aethelflaed** [inventaire/inventaire#437]
A shelf can be created using only a name, but when I want to edit it, it's not possible to change anything if I don't add a description.

The client-side error message is:

> invalid description: null

This is posted on the server repository because the console clearly displays a 402 response for the request `https://inventaire.io/api/shelves?action=update` 

Additionally, I have 

> Missing translation for key: "invalid description: null"

Putting a description clears the problem.

**Comment by maxlath** [comment]
I wrote a patch (bc3b8cd) that is now online, @Aethelflaed @PtiBzh can you confirm that it fixes the issue you encountered?

**Comment by Aethelflaed** [comment]
I confirm the issue is fixed, I edited existing a new shelves and any combination of action works ;-) Thanks !

**Comment by PtiBzh** [comment]
Thanks for the reactivity!
