### ISSUE TITLE
Connection button non reachable on a profile page

### ISSUE THREAD

**Issue by PetiPandaRou** [inventaire/inventaire#44]
When I click on a profile link, the website propose to connect (it's logical).
But the button is not reachable (more problematic).
![screenshot](https://cloud.githubusercontent.com/assets/323248/10214844/351fe2da-681c-11e5-92dd-63d8077d51ab.png)

**Comment by maxlath** [comment]
hi, thank you for reporting this issue!
It's actually made on purpose: you can't connect to someone if you aren't logged in. But from your confusion, I guess it could be clearer: should there be just the text inviting to login and no button in the background?

**Comment by PetiPandaRou** [comment]
Ok, I weren't connected. But when the user has a description, it's quite ugly:
![capture d ecran 2015-10-08 a 09 33 09](https://cloud.githubusercontent.com/assets/323248/10360274/b4e08e1a-6d9f-11e5-8380-61d32cf25835.png)

**Comment by maxlath** [comment]
indeed ^^

**Comment by maxlath** [comment]
have been trying to fix this issue: what do you think of that option?
![capture du 2015-12-10 11 54 50](https://cloud.githubusercontent.com/assets/1596934/11713642/ed67bd82-9f34-11e5-994f-1d77dc55405f.png)
not especially pretty but cleaner right?

**Comment by PetiPandaRou** [comment]
Yeah it's better.
Don't close the bug, I'll try to do something better for that (after New Year).

**Comment by maxlath** [comment]
awesome! :)
The files you are looking for are those modified in this commit: https://github.com/inventaire/inventaire-client/commit/a10767fa37911b729acbc045e077c164d5fa20a9 (so in the [client repo](https://github.com/inventaire/inventaire-client))
