### ISSUE TITLE
Only share a specific shelf with a group

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#453]
### Usecase
As a user with a "books for kids" shelf in my inventory and as a member of "the parent's group", I would like to share only this shelf with the group, in order to not display my erotic books on the group's page.

### Specifications
- a user can share several shelves with one group
- a user can share a shelf with several groups
- no shelf shared is considered the default behavior : every items are shared with the group
- only shelves with a visibility set to "public" or "groups and friend" can be shared to groups

### Possibles implementations
1. On the group document, besides (or within) the `members` key would be a `shelves` key, allowing a group page to query `byShelvesAndListing` couch view. 

External events which would need care:
- When a member leave a group, shelves ids must be removed from the group document
- When a shelf is deleted, all groups where the shelf's owner is a member must be updated

pro: performance of group inventory view display, as shelves can directly be queried from the group
con: quite some dev work to manage external events

2. On the shelf document, there would be `groups` key, with a new couch view which may be called `byShelvesAndGroups`.

- When a member leave a group, member's shelves.groups must be updated  

pros&cons: the opposite of suggestion 1. : easy life cycle management but might be too slow to load at a reasonable time for the 2020 web.

3. a middle-ground solution : the user document holds an object with groups as keys and list of shelves as values, using the actual `byShelvesAndListing` view

- When a member leave the group, group key is deleted
- When a shelf is deleted, user doc is updated

**Comment by maxlath** [comment]
Implementation 2 seems cleaner.
I feel like this should work with items and shelves `listing` attribute: what about turning `listing` into some list attribute that could contain:
- `public` = everybody
- `network` = `friends` + all groups the user belongs to
- group ids
- `friends` (sort of like a dynamic group made of all your direct contacts)
- empty or `private` = nobody but you

**Comment by jum-s** [comment]
In the case of a user who does not share their shelf but is a group member, suggestion 2. means to wait for the shelves (in order to find out that `shelf.groups` is empty) and only then load the items.

On your second point, why do you think that would be necessary ? I like the idea to hack this "refine group sharing granularity" by going though the shelves so that there is no "urgent" need to modify how listing is currently implemented. But maybe im missing something ?

**Comment by maxlath** [comment]
I would actually prefer to work on getting visibility granularity "right", including possibly by revolutionizing listing values if needed ^^

My motivation to explore the possibility of a unique `visibility` attribute (gathering both the current `listing` and the proposed `groups` attributes), is to centralize the control of an item or a shelf visibility, as, if I get it right, both attributes would be used to determine the visibility. Some use-cases that would need a form of coordination if we were to keep `listing` and `groups` separated:
* a shelf has `listing=public` and `groups=somegroupid`, the `groups` value wouldn't change anything, everybody could still see that shelf, right?
* same with `listing=network`
* with `listing=private`, that actually kind of works: (à la `ufw`)
  * rule 1 (`listing`): deny all
  * rule 2 (`groups`): allow groupA and groupB

**Comment by jum-s** [comment]
> I would actually prefer to work on getting visibility granularity "right", including possibly by revolutionizing listing values if needed ^^

i dont see the need for a revolution here.

> My motivation to explore the possibility of a unique `visibility` attribute (gathering both the current `listing` and the proposed `groups` attributes), is to centralize the control of an item or a shelf visibility, as, if I get it right, both attributes would be used to determine the visibility. Some use-cases that would need a form of coordination if we were to keep `listing` and `groups` separated:

in this case i think centralization makes the visibility quite complex to handle, while we could dodge this complexity by going through shelf group sharing without having to ask any question about how a single item is shared with groups.
 
>     * a shelf has `listing=public` and `groups=somegroupid`, the `groups` value wouldn't change anything, everybody could still see that shelf, right?

No, i have several public shelves, but i would like to only share a specific public shelf with a specific group (my enginners shelf to share

>     * same with `listing=network`
> 
>     * with `listing=private`, that actually kind of works: (à la `ufw`)
>       
>       * rule 1 (`listing`): deny all
>       * rule 2 (`groups`): allow groupA and groupB

**Comment by jum-s** [comment]
> I would actually prefer to work on getting visibility granularity "right", including possibly by revolutionizing listing values if needed ^^

i dont see the need for a revolution, here.

> My motivation to explore the possibility of a unique `visibility` attribute (gathering both the current `listing` and the proposed `groups` attributes), is to centralize the control of an item or a shelf visibility, as, if I get it right, both attributes would be used to determine the visibility. Some use-cases that would need a form of coordination if we were to keep `listing` and `groups` separated:

in this case i think centralization makes the visibility quite complex to handle at the item level. While at the shelf level, it would actually allow the user to make fine sharing possibilities without having to ask any question about how a single item is shared with groups.

>     * a shelf has `listing=public` and `groups=somegroupid`, the `groups` value wouldn't change anything, everybody could still see that shelf, right?

No, i have several public shelves, but i would like to only share a specific public shelf with a specific group, but not the others.

>     * same with `listing=network`

idem

>     * with `listing=private`, that actually kind of works: (à la `ufw`)
>       
>       * rule 1 (`listing`): deny all
>       * rule 2 (`groups`): allow groupA and groupB

i would claim that a private item is a private item (yeah...) and thus shall not be shared with any one even though it belongs to a public shelf shared with some groups

**Comment by jum-s** [comment]
okay this issue does not seem very mature, I will leaving aside for the moment to let us have tome to think more about it

**Comment by jum-s** [comment]
related #454 but in conflict with

**Comment by jum-s** [comment]
15 months later, a [milestone](https://wiki.inventaire.io/wiki/NGI_Zero_Discovery_grants#Finer_privacy_settings) is set to "fine-tune items visibility".
As a discussion between max and i occurred a week ago, we agreed to have specifications as follow (maybe subjected to change while implementation is going on, but it could help document the milestone)

moving db store from current `"listing": "private",` to an **array like value** which may contain the following elements:

- an empty array: meaning only the owner can see the item (currently `inventorying`)
- `public` which would override every other elements of the array
- `friends` which would trigger a dynamically generated array of user ids
- any group id which would exclude every other groups the user is a member of
- `network` which would trigger a dynamically generated array of group ids

this way a user may share books with:
- all their groups or with some of their groups only
- or/and all their friends, 
- or everyone 
- or no one

@maxlath feel free to update this list according to our conclusion of the discussion we had, my memory may be not as precise as i would like it to be

**Comment by maxlath** [comment]
done in https://github.com/inventaire/inventaire/pull/624 and https://github.com/inventaire/inventaire-client/pull/322, as well as for items in https://github.com/inventaire/inventaire/pull/632 and https://github.com/inventaire/inventaire-client/pull/332 :tada:
