### ISSUE TITLE
create an admin-only endpoint to retrieve the latest created users

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#455]
to allow admins to easily detect and delete spammers accounts.

Some pointers:
* There is already a `byCreation` CouchDB view that could be reused
* Having pagination would be a nice to have, as that would make it easy to create an infinite scroll on the client side ([see notifications for a pagination example](https://github.com/inventaire/inventaire/blob/master/server/controllers/notifications.js#L13-L27))
* Limiting access to admins only should be done from the object passed to `ActionsControllers`, see [how it's done for entities routes](https://github.com/inventaire/inventaire/blob/878697a/server/controllers/entities/entities.js#L20-L23)
* To write the API tests, you can use the `adminReq` function, see [this example](https://github.com/inventaire/inventaire/blob/b1a7ee0/tests/api/entities/activity.test.js)

**Comment by hasheemismath** [comment]
Can I help you solve this issue?

**Comment by maxlath** [comment]
@hasheemismath sure! Feel welcome to ask for help (here or in the [chat](https://wiki.inventaire.io/wiki/Communication_channels#Chat)) if you struggle to setup your development environment or need more pointers on this specific issue
