### ISSUE TITLE
Enable open groups

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#456]
Like [mobilizon](https://framagit.org/framasoft/mobilizon/-/releases/1.0.1) recently did, group settings would have an option to pick if the group is open to new members or on invite only (like today's implementation).

Default would be on invite.
In case of an open group, there would be no request process, users would become member when pressing "Join the group" (today named "Request to join the group").

**Comment by maxlath** [comment]
Some thoughts:
* I imagine that open groups will strenghten the need for finer visibility settings: having no way to show certain items or shelves to friends but not to members of an open group is getting very sub-optimal. That basically mean that as long as you are part of an open group, I can unilaterally decide to see as much of your inventory as your friends.
* [applies to non-open groups, but might be more critical on open groups] Should we set a maximum number of members? That can wait but I guess we might experience performance issues in both the server and client with very large groups.
* We will need some UI elements to make those settings (`open` but also `searchable`) known to people before they join a group
* Changes on those settings by a group admin should trigger a notification for all members

**Comment by jum-s** [comment]
i agree on the notification part.
I will work on the ui, im thinking of triggering an alert modal when clicking on the "join group"  button. A text that could say "since this group is open, every users can freely join this group and see your items which have a "friends and groups" sharing settings. Would you like to continue and join this group ?" 
On the visibility settings, i think that's par of other issues. Same for the maximum group member (which we could setup when the server is too stressed ?)

**Comment by maxlath** [comment]
done in https://github.com/inventaire/inventaire/pull/460 and https://github.com/inventaire/inventaire-client/pull/240
