### ISSUE TITLE
Feature: also see books of non-friends in your region

### ISSUE THREAD

**Issue by fkooman** [inventaire/inventaire#47]
It would be nice to be able to see books people are lending in your general area. Also nice way to get to know new people! Or is it really only meant as a lending service between friends?

**Comment by maxlath** [comment]
Thanks for this issue too :)
Geolocation is a [very current topic](https://trello.com/c/TVwHQxBC/14-books-geolocation)!! I'm gathering bricks to make it happen:
* working on setting up [geocouch](https://github.com/couchbase/geocouch) for querying geo coordinates in Couchdb
* playing with [leaflet](https://leafletjs.com) to use [openstreetmap](http://openstreetmap.org)/[mapbox](https://www.mapbox.com) for cards

more on all that soon hopefully :)

**Comment by maxlath** [comment]
done!
users nearby https://inventaire.io/network/users/nearby
groups nearby https://inventaire.io/network/groups/nearby
books of the users nearby https://inventaire.io/inventory/nearby
