### ISSUE TITLE
Series ordinal is not a standalone property in Wikidata anymore

### ISSUE THREAD

**Issue by nortix** [inventaire/inventaire#472]
When editing an entry with the property P179:Part of the series it should contain P1545:series ordinal as a qualifier. According to the guidelines it's not a standalone property anymore.

![screen-0001](https://user-images.githubusercontent.com/36004906/103274752-b4c19280-49c2-11eb-8021-3f15b9b68f29.png)

**Comment by maxlath** [comment]
P1545 should indeed be used as a qualifier of a P179 claim, but that's not possible in Inventaire yet due to the current [absence of qualifiers in our data model](https://github.com/inventaire/inventaire/issues/145)

**Comment by nortix** [comment]
Thank you. Seems like I haven't searched deeply enough. You can delete this issue or merge it.

**Comment by maxlath** [comment]
no worries :) we can close it in favor of #433

**Comment by maxlath** [comment]
Following #565, editing simple cases (1 serie, 1 ordinal) from Inventaire should now work and respect Wikidata recommendation to set P1545 as a qualifier. Cases where there a work is part of 2 series still doesn't work/can't be edited from Inventaire though
