### ISSUE TITLE
search: exact matches should work

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#473]
ex: [wd:Q182847](https://inventaire.io/entity/wd:Q182847)

* [author: "Baudrillard"](https://inventaire.io/api/search?types=humans&search=Baudrillard&lang=fr&limit=50): wd:Q182847 comes 1st
* [author: "Jean Baudrillard"](https://inventaire.io/api/search?types=humans&search=Jean%20Baudrillard&lang=fr&limit=50): wd:Q182847 comes only 36th, the results being flooded by "Jean"s with [higher popularity scores](https://inventaire.io/api/entities?action=popularity&uris=wd:Q309240|wd:Q1343882|wd:Q574856|wd:Q3164657|wd:Q428160|wd:Q3170138|wd:Q3164666|wd:Q2708564|wd:Q123706|wd:Q3089290|wd:Q2705993|wd:Q2474670|wd:Q177411|wd:Q3165136|wd:Q1685793|wd:Q715206|wd:Q3167419|wd:Q123190|wd:Q3167174|wd:Q5829|wd:Q3168813|wd:Q3170128|wd:Q16267939|wd:Q6527|wd:Q707328|wd:Q1097651|wd:Q2329943|wd:Q179025|wd:Q773042|wd:Q27921811|wd:Q1685027|wd:Q1339|wd:Q233584|wd:Q3168741|wd:Q3167045|wd:Q182847), despite the exact label match

**Comment by jum-s** [comment]
definitly. Exact match of the whole text search shall be boosted

**Comment by maxlath** [comment]
adding the "critical" label after discussing with a data contributor who struggles to find the right authors, and sometimes then re-creates the author

**Comment by jum-s** [comment]
I can put this afternoon on it i your fine with it ?

**Comment by maxlath** [comment]
sure, I can't work on it now, so feel free to claim it

**Comment by jum-s** [comment]
well exact match do work now

**Comment by maxlath** [comment]
the local entities are easily not found despite an exact match, when their label share some words with Wikidata entities (despite the absence of popularity on those)

**Comment by jum-s** [comment]
[opened a new issue](https://github.com/inventaire/inventaire/issues/485), as this one was labeled critical and was with an wikidata entity example
