### ISSUE TITLE
Elasticsearch licensing change

### ISSUE THREAD

**Issue by Aethelflaed** [inventaire/inventaire#483]
Elastic [recently announced](https://www.elastic.co/blog/licensing-change) a coming switch to [SSPL](https://www.mongodb.com/licensing/server-side-public-license).

Can this become a problem for inventaire and its licensing?

Is there some viable alternatives that may keep the project and its dependencies under OSI approved licenses?

**Comment by jum-s** [comment]
Thanks for the notification. I don't think this change will impact inventaire, as we barely [start to use](https://github.com/inventaire/inventaire/pull/478) Elasticsearch features (which are more than the default basic ones) and are quite far from be able to bring modification to Elastic

The [FAQ](https://www.elastic.co/pricing/faq/licensing) makes it quite clear:

> If you download and use our default distribution of Elasticsearch and Kibana, nothing changes for you.

which, as far as i know, is Inventaire case.

As a TDLR : 

> SSPL allows free and unrestricted use and modification, with the simple requirement that if you provide the product as a service to others, you must also publicly release any modifications as well as the source code of your management layers under SSPL.

Finally, in my opinion, i agree with them when they state that "this change allows us to be even more open", and, i long as this is true, i would like to continue using Elasticsearch even if it forces us to change the license of some code.

Im closing this issue (but, reader, feel free to reopen it if you feel im wrong)

**Comment by maxlath** [comment]
> *this change most likely has zero effect on you*
>
> — [Amazon: NOT OK - why we had to change Elastic licensing](https://www.elastic.co/fr/blog/why-license-change-AWS)

**Comment by jum-s** [comment]
some more critical view one the matter https://drewdevault.com/2021/01/19/Elasticsearch-does-not-belong-to-Elastic.html

**Comment by maxlath** [comment]
[Elasticsearch adds an AGPL license](https://www.elastic.co/fr/blog/elasticsearch-is-open-source-again) :tada:
