### ISSUE TITLE
Allow to add Edition URL

### ISSUE THREAD

**Issue by arkhi** [inventaire/inventaire#484]
A Publisher might provide information on a dedicate page, for example: https://www.laplage.fr/catalogue/la-pollution-cachee-des-choses/

The page often lists the ISBN, number of pages, dimensions and maybe other information and related editions.

I think that, as a first-hand source, this would be a useful information to have on an edition.

**Comment by Em-AK** [comment]
Then I guess a process is needed to crawl these webpages from time to time and somehow report broken links to the instance admins.

:wink: : here is the new link for the example provided by @arkhi https://www.laplage.fr/produit/249/9782842219055/la-pollution-cachee-des-choses

**Comment by maxlath** [comment]
done with d7bf825 and https://github.com/inventaire/inventaire-client/commit/92fad430, now online, see [example](https://inventaire.io/entity/isbn:9782842219055/edit)
