### ISSUE TITLE
 Local entities are easily not found despite an exact match

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#485]
when their label share some words with Wikidata entities (despite the absence of popularity on those)

**Comment by maxlath** [comment]
examples:
- ["Les dessous de l'odyssée"](https://inventaire.io/api/search?types=works&search=Les%20dessous%20de%20l%27odyss%C3%A9e&lang=fr&limit=10&filter=inv) doesn't rank the exact match [`inv:6a281fe05049d7632c5fada86993c7c3`](https://inventaire.io/entity/inv:6a281fe05049d7632c5fada86993c7c3) first (even with `filter=inv`)
