### ISSUE TITLE
Search only for exact match

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#486]
It could be nice to only search for exact match with a dedicated query builder.

Use cases: 
- allow to search for duplicates without having to filter noises (ie. to create tasks)
- allow users to query an exact match with quote syntax (`"foo"`), which seems to be a common usage around the web.

**Comment by maxlath** [comment]
additionally, that exact match could be more restrictive on the queried fields, only including labels (and possibly aliases), but not descriptions

**Comment by jum-s** [comment]
today fuzzy searches are only used for [social queries](https://github.com/inventaire/inventaire/blob/master//server/controllers/search/lib/social_query_builder.js#L6). 
since searches a separated between entities and social ones, i would like to restrict this issue to allow exact match for entities only.

**Comment by maxlath** [comment]
done in #495
