### ISSUE TITLE
emails background color misinterprated by email clients

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#494]
when i use an email client with dark theme, email sent by the mailer are set with a [whiteish bgcolor](https://github.com/inventaire/inventaire/blob/master//server/lib/emails/views/partials/header.hbs#L6)
so, when I reply to this kind of email (lets say a feedback email), then the background is set to whiteish but the text color is also set white by default

![2021-02-05_17-21](https://user-images.githubusercontent.com/5363918/107059806-28c73580-67ce-11eb-8891-8cce25b9a61c.png)

could we either delete the `gbcolor` or add a `color` attribute ?

**Comment by jum-s** [comment]
commit is already on master

**Comment by maxlath** [comment]
new attempt at being easy on dark mode: 14c7f2f7
