### ISSUE TITLE
implement server monitoring

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#5]
http://newrelic.com/ ?
http://mmonit.com/monit/ ?

**Comment by simison** [comment]
Great! I'm also looking for something to replace NewRelic (which is great but not FOSS). Tossing some more links in:

http://projects.nuttnet.net/hummingbird/
http://nodetime.com/
http://lorenwest.github.io/node-monitor/
http://munin-monitoring.org/ / https://github.com/benbuckman/nodejs-munin

http://www.quora.com/What-are-the-alternatives-to-newrelic
http://www.quora.com/What-are-good-ways-to-monitor-a-node-js-server-in-real-time

**Comment by almereyda** [comment]
Have you heard about the new [BOSS](https://www.npmjs.com/package/boss-cli)?

**Comment by simison** [comment]
@almereyda I use https://www.phusionpassenger.com/ for that stuff.

**Comment by almereyda** [comment]
@simison Now I see why ... http://shout-irc.com/docs/deployment/passenger.html ... simplicity in config, eh? Is it using sockets internally?

**Comment by maxlath** [comment]
@simison well, Passenger is a bit too magic/not modular enough for me: it might be fast to install but I feel like a passenger (ahah) in my own car, not knowing what is happening and thus unable to debug (reminds me of when I broke my teeth on Meteor ;) )

@almereyda Boss could be the right tool but it doesn't seem to support coffeescript at the moment: I opened [an issue on that](https://github.com/tableflip/boss/issues/31)

**Comment by pierreozoux** [comment]
I use uptime robot (non foss) atm, but plan to switch to [uptime](http://www.redotheweb.com/uptime/). Once I host it for me, I can host it for others also :)
You can foolow the issue here: https://github.com/IndiePaaS/IndiePaaS/issues/24

**Comment by maxlath** [comment]
thanks! will have a look at that

**Comment by maxlath** [comment]
server monitoring isn't that needed for now, closing until it make sense

**Comment by pierreozoux** [comment]
I know a bit more about the subject now :)

You have 3 kinds of monitoring:
  - server metrics
  - Aplication Performance Monitoring (APM) (server and browser side)
  - application logs 

The standard stack nowadays is the following:
  - prometheus/grafana for metrcis/alerting
  - [prom](https://blog.risingstack.com/node-js-performance-monitoring-with-prometheus/) or [elastic APM](https://www.elastic.co/solutions/apm) for server side APM and [sentry](https://sentry.io/welcome/) for client side.
  - elastic for application logs

I hope it helps, I can help if/when needed :)

Have a nice day!
