### ISSUE TITLE
Button to delete account is broken?

### ISSUE THREAD

**Issue by frimelle** [inventaire/inventaire#51]
I had a test account and wanted to delete it. I clicked on the "Danger Zone" "delete your account"-Button, a pop-up comes up, I can enter a text, when clicking the button, it seemed like nothing happens. I clicked it again, entered the text again, again nothing seemed to happen. Left the tab open and came to github to report the issue. Next time I checked the Inventaire tab, I seem to be logged out and on my proper account, I wasn't able to find the test account either. Seems to work but there seems to be an issue, too. Confusing.

**Comment by maxlath** [comment]
thanks for reporting, I received loads of account deleted messages so I guess it successfully tried to delete several times but the UI didn't update to reflect it. This isn't really surprising given I had an issue with the way accounts where deleted making CouchDB go mad, I thus made a changed to prevent it but without properly testing on the client-side: doing that asap :)
