### ISSUE TITLE
Title background for settings picture missing

### ISSUE THREAD

**Issue by DougInAMug** [inventaire/inventaire#519]
https://inventaire.io/groups/kanthaus

![Screenshot from 2021-04-08 16-15-50](https://user-images.githubusercontent.com/13798767/114042847-1331c300-9886-11eb-8216-f3346eb0f879.png)

https://inventaire.io/groups/kanthaus/settings

![Screenshot from 2021-04-08 16-16-19](https://user-images.githubusercontent.com/13798767/114042906-22b10c00-9886-11eb-81cf-8fd2fac6d8f4.png)

*Note the white letters 'cut out' from the black in the picture.* The missing background for the title on the settings view of the picture makes pictures with lots of white unsafe.

(Apologies if I brought this up before)

**Comment by maxlath** [comment]
should be fixed now (https://github.com/inventaire/inventaire-client/commit/8912fcea8efc72328adb1fbd757eb91b25e32a13)
