### ISSUE TITLE
remove the Persona signup option

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#56]
[persona.org is shutting down](https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers) on November 30th 2016, and this being the only credible provider (afaik), letting users signup with Persona seems now a bad thing.

Meanwhile, logging in with Persona should stay possible for some more months but Persona users should be invited to move to classic username/password login, which can be done by clicking "Forgot my password"

**Comment by yalamerde** [comment]
Yes, it's also breaking on Vivaldi and spins forever without opening the popup.
But which other OAuth providers could you consider? Twitter at least? GitHub may be too geeky ... Google and Facebook too evil.
