### ISSUE TITLE
Add more information on AP actors

### ISSUE THREAD

**Issue by roipoussiere** [inventaire/inventaire#579]
There is generally way more information on inventaire.io than on the related AP actor.

More information could be added on ActivityPub profile metadata, including links to related AP actors.

### [On inventaire.io](https://inventaire.io/entity/wd:Q46248)

> **Terry Pratchett**
>
> British fantasy author
> 1948   -   2015
>
> genre: fantasy, comic fantasy
> country of citizenship: United Kingdom
> languages spoken, written or signed: English
> educated at: John Hampden Grammar School
> occupation: writer, novelist, journalist, screenwriter, science fiction writer, children's writer, author
> award received: Officer of the Order of the British Empire, Margaret Edwards Award, [...]
> influenced by: P. G. Wodehouse, G. K. Chesterton, Lloyd Alexander, Jack Vance, Tom Sharpe
> website: www.terrypratchettbooks.com
> twitter: @terryandrob
>
> Sir Terence David John Pratchett (28 April 1948 – 12 March 2015) was an English humorist, [...]

### [On ActivityPub](https://mastodon.tetaneutral.net/web/accounts/107405334559992187)

> **Terry Pratchett**
> @wd-Q46248@inventaire.io
> |  |  |
> | --- | --- |
> | inventaire.io | https://inventaire.io/entity/wd:Q46248 |
> | wikidata.org | https://www.wikidata.org/wiki/Q46248 |
> 
> bio: British fantasy author

### Suggestion

> **Terry Pratchett**
> @wd-Q46248@inventaire.io
> |  |  |
> | --- | --- |
> | brief | British fantasy author |
> | inventaire.io | https://inventaire.io/entity/wd:Q46248 |
> | wikidata.org | https://www.wikidata.org/wiki/Q46248 |
> | birth and death | 1948   -   2015 |
> | genre | fantasy, comic fantasy |
> | country of citizenship | United Kingdom |
> | languages spoken, written or signed | English |
> | website | www.terrypratchettbooks.com |
> | twitter | @terryandrob |
> 
> bio: Sir Terence David John Pratchett (28 April 1948 – 12 March 2015) was an English humorist, [...]

### [On inventaire.io](https://inventaire.io/entity/wd:Q3213929)

> **La Volte**
>
> maison d'édition française
>
> website: lavolte.net
> twitter: @EditionsLaVolte
> facebook: editions.lavolte
> La Volte est une maison d'édition indépendante française spécialisée dans les littératures de l'imaginaire, [...]

### [On ActivityPub](https://mastodon.tetaneutral.net/web/accounts/107405334874392201)

> **La Volte**
> @wd-Q3213929@inventaire.io
> |  |  |
> | --- | --- |
> | inventaire.io | https://inventaire.io/entity/wd:Q3213929 |
> | wikidata.org | https://www.wikidata.org/wiki/Q3213929 |
>
> bio: -

### Suggestion

> **La Volte**
> @wd-Q3213929@inventaire.io
> |  |  |
> | --- | --- |
> | brief | maison d'édition française |
> | website | lavolte.net |
> | twitter | @EditionsLaVolte |
> | facebook | editions.lavolte |
> | inventaire.io | https://inventaire.io/entity/wd:Q3213929 |
> | wikidata.org | https://www.wikidata.org/wiki/Q3213929 |
>
> bio: La Volte est une maison d'édition indépendante française spécialisée dans les littératures de l'imaginaire, [...]

### [On inventaire.io](https://inventaire.io/entity/isbn:9780544272996)

> **What If?**
> Serious Scientific Answers to Absurd Hypothetical Questions
> 
> edition of: What If?
> author: Randall Munroe
> language: English
> date of publication: 2014
> number of pages: 303
> ISBN-13:978-0-544-27299-6
> ISBN-10:0-544-27299-4

### [On ActivityPub](https://mastodon.tetaneutral.net/web/accounts/107411650067958611)

> **What If?**
> @wd-Q20065110@inventaire.io
> |  |  |
> | --- | --- |
> | inventaire.io | inventaire.io/entity/wd:Q20065110 |
> | wikidata.org | www.wikidata.org/wiki/Q20065110 |
>
> bio: non-fiction book by Randall Munroe, 2014

### Suggestion

add the book image to the AP profile ;)

> **What If?**
> @wd-Q20065110@inventaire.io
> |  |  |
> | --- | --- |
> | inventaire.io | inventaire.io/entity/wd:Q20065110 |
> | wikidata.org | www.wikidata.org/wiki/Q20065110 |
> | author | Randall Munroe (@wd-Q285048) |
> | language | English |
> | date of publication | 2014 |
> | number of pages | 303 |
> | ISBN-13 | 978-0-544-27299-6 |
> | ISBN-10 | 0-544-27299-4 |
>
> bio: What If?: Serious Scientific Answers to Absurd Hypothetical Questions is a non-fiction book by Randall Munroe in which the author answers hypothetical science questions sent to him by readers of his webcomic, xkcd. The book contains...

**Comment by jum-s** [comment]
properties not done yet:
- birth/death of authors
- isbn-10 and 13
- new properties(?) see #479

**Comment by jum-s** [comment]
most of it is now in production 
closing in favor of #612
