### ISSUE TITLE
Add Open Library ID code field

### ISSUE THREAD

**Issue by xplosionmind** [inventaire/inventaire#591]
As a step towards implementing #532, it would be really useful to connect books to the OpenLibrary catalogue by entering the OpenLibrary ID for each book.

This is a specific example of that requested in #112: linking the Inventaire entry to other catalogs across the web.

**Comment by jum-s** [comment]
This is already possible with the `entities` endpoint : https://inventaire.io/api/entities?action=by-uris&uris=isbn:9783882200041
Currently [800+](https://query.inventaire.io/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%20%20%3Fentities%20wdt%3AP648%20%3FOLid%20.%0A%7D) inventaire entities have an OLid property ([P648](https://www.wikidata.org/wiki/Property:P648)), plus all wikidata items inventaire recognizes: for example, the [12000+](https://query.wikidata.org/#SELECT%20%2a%20WHERE%20%7B%0A%20%3Fentities%20wdt%3AP648%20%3FOLid%20.%20%0A%20%20FILTER%28STRENDS%28%3FOLid%2C%20%22W%22%29%29%0A%7D) works with the same P248 property (ie: https://inventaire.io/api/entities?action=by-uris&uris=wd:Q109617045)

**Comment by maxlath** [comment]
This should have been solved by https://github.com/inventaire/inventaire-client/pull/339

You should now find an OpenLibrary field in the entity editor:
![Capture d’écran du 2023-03-03 14-24-43](https://user-images.githubusercontent.com/1596934/222731563-703f33cd-926b-46aa-b61a-f4eac535d2bf.png)
