### ISSUE TITLE
Group creation failed

### ISSUE THREAD

**Issue by jibe-b** [inventaire/inventaire#597]
Hello!

I just tried to create a group: ![image](https://user-images.githubusercontent.com/6146483/149749694-2a98d8fa-e4c9-467d-86de-5fbf56b18ded.png)

but nothing happens on the page.

When I visit https://inventaire.io/network/groups/create, in the console the following appears:

![Capture d’écran de 2022-01-17 11-05-21](https://user-images.githubusercontent.com/6146483/149749824-49aaab13-ed73-4892-a396-8b4f228f0bf1.png)

I am not in a hurry to create this group but I may propose it to a nice community.

**Comment by jum-s** [comment]
thx for reporting ! 
this should be fixed now with 791ae2

**Comment by jibe-b** [comment]
It is!
![Capture d’écran de 2022-01-17 15-53-04](https://user-images.githubusercontent.com/6146483/149791715-f05892ff-2663-447c-9722-ff6b43297f12.png)


Thanks for acting fast!
