### ISSUE TITLE
Q1391417 should be useable for books

### ISSUE THREAD

**Issue by Hildepont-0** [inventaire/inventaire#605]
Hi,
Inventaire doesn't support 'specialized dictionaries' from wikidata (Q1391417).
Look for instance at ' Dictionnaire des corsaires et des pirates' (Q110952805).

**Comment by maxlath** [comment]
done in c682e57, but that's part of a larger problem, see #414

**Comment by Hildepont-0** [comment]
It works fine, thank you !
