### ISSUE TITLE
create a Docker image to ease deployment

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#61]
A few things I would like to discuss:
- should inventaire have Docker image? ([some seem to think that yes](https://twitter.com/niamtokik/status/699873948545245184))
- how would the dependency with couchdb/geocouch be handled? (Docker noob question)
- [Minimal Docker Containers for Node.js](https://blog.risingstack.com/minimal-docker-containers-for-node-js) any thoughts on that?

cc @almereyda @niamtokik

**Comment by almereyda** [comment]
* The Alpine looks good. Had no problems with their base images so far.
* GeoCouch lives currently only in https://github.com/14mmm/docker-geocouch/ and https://hub.docker.com/r/almereyda/geocouch/.  
Its dependency is most easily maintained by [`docker-compose`](https://docs.docker.com/compose/).
  * Official CouchDB image will exist soon. `github.com/docker-library/official-images/pulls/1288`
  * Some work is being done to get GeoCouch in, too. `github.com/klaemo/docker-couchdb/pull/49`
* Else: Why not? It's handy when it comes to creating repeatable local development environments and easily replicating similar setups in production.

**Comment by niamtokik** [comment]
Before doing this kind of process, a really good documentation is needed, at least, a functional one for a standard installation and configuration. If someone can't deploy easily an image from scratch (w/ or w/o documentation), its not a good idea to create a docker image.

Currently, inventaire.io just didn't work on my servers (void-linux and freebsd). Lot of small things (the devil is in the detail) need to be refactored (hostname configuration, couchdb deployment, rethinking about script compatibility, lot of deps, doesn't work on some arch like arm).

The other important thing before doing docker image, is to create tools for automatic deployment via [salt](https://saltstack.com/), [puppet](https://puppetlabs.com/) or [chef](https://www.chef.io/chef/). This will be really useful for testing on other distributions or just for validate merge and commit.

**Comment by rgarrigue** [comment]
:+1:  for a Docker. I'ld also recommand alpine for the minimal size. You can include all dependencies + inventaire in one docker, or split everything, couchdb in a docker, inventaire in another... no big deal here.

I don't mind working on the topic, got some experience here. @maxlath, would you mind providing a raw script, basically your bash history for installing Inventaire on a raw ubuntu server ?

**Comment by maxlath** [comment]
@rgarrigue I already have something like a big scratchpad where I have been copying and pasting installation commands so far. I got to find the time to clean it, decouple it from my own environment, probably also remove the credentials lying around here and there, and that should do for a start ^^
Will do asap

**Comment by rgarrigue** [comment]
Good. I started a draft [here](
https://github.com/rgarrigue/docker-inventaire), I'm awaiting your
scratchpad to resume my work.

2016-04-14 17:19 GMT+02:00 maxlath <notifications@github.com>:

**Comment by maxlath** [comment]
yeay! sorry for letting this issue sleep, I finally found the time to get things cleaner :)
I started a new repo [inventaire-deploy](/inventaire/inventaire-deploy) with the Ubuntu implementation in the master branch, but letting the door open for other implementations to work on other branches. How does that look?

**Comment by maxlath** [comment]
* [Karrot docker-compose](https://github.com/yunity/karrot-docker/blob/master/docker-compose.yml)
* [How to run npm install as non-root from a Docker container](http://lebenplusplus.de/2018/03/15/how-to-run-npm-install-as-non-root-from-a-docker-container/)

**Comment by jum-s** [comment]
[docker-inventaire](https://github.com/inventaire/docker-inventaire) is now an official repo !
