### ISSUE TITLE
German translation for “federated” is wrong

### ISSUE THREAD

**Issue by sebilasse** [inventaire/inventaire#620]
I can choose to federate with ActivityPub in my Settings which is super awesome. 
Unfortunately the german translation is wrong and very misleading, currently it reads “Federführend” which means “leading” or ”in charge” …

The german word for "to federate" is "Föderieren", 
the translation for "federating" is "Föderierend"

**Comment by maxlath** [comment]
and how would you translate "fediversable"?

**Comment by sebilasse** [comment]
well, fediversable is a nice but artificial word and hard to translate. 
I mean, technicall it would be "federatable" but I understand and support the desire to have "fediverse" inside.

So let's compare Universe to Fediverse …
The word "universal" is the same in German but what would "universable" be? :)
Universe is Universum.
Fediverse is Fediversum. 

So, "fediversal" or "fediversabel" might come close.
The words ending in "able" usually end in "abel" in German.

Like "acceptable" === "akzeptabel"

**Comment by schmittlauch** [comment]
I'd honestly even have trouble understanding *fediversable* in an English context. How about *Fediverse integration* instead, which is also easily translatable?

**Comment by maxlath** [comment]
["fediversable" was replaced by "Fediverse integration"](https://github.com/inventaire/inventaire-client/commit/b086300), the change should be online now
