### ISSUE TITLE
Welcome page listing is broken

### ISSUE THREAD

**Issue by AutomCoding** [inventaire/inventaire#644]
The listing of recently added items on the welcome page has broken down. No errors in console, except for a warning that the string "There is nothing here" lacks translation.

![Screenshot_20220907_020748](https://user-images.githubusercontent.com/40275136/188761336-47600b82-1b30-4741-b7b9-56b6f664fb6a.png)

```
,___,
[-.-]   I've been expecting you, Mr Bond
/)__)
-"--"-
Want to make Inventaire better? Jump in!
Project chat: https://wiki.inventaire.io/wiki/Communication-channels#chats
Wiki: https://wiki.inventaire.io
Design: https://roadmap.inventaire.io
Code: https://git.inventaire.io/inventaire
------ env_config.js:17:10

Missing translation for key: There is nothing here i18n.js:32:12
```

**Comment by maxlath** [comment]
Thanks for reporting :sweat_smile:
Fixed by https://github.com/inventaire/inventaire-client/commit/aab9406
