### ISSUE TITLE
use Couchdb sessions instead of Basic Auth

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#65]
from [CouchDB doc on Authentication](http://docs.couchdb.org/en/1.6.1/api/server/authn.html)

> Basic Auth could hurt operation performance since CouchDB must compute password hash with every request

[using-cookie-authentication with nano](https://github.com/dscape/nano#using-cookie-authentication)

**Comment by almereyda** [comment]
Would this be reusable by `data.transformap.co`, i.e. could we implement it there and it can be ported here?

**Comment by maxlath** [comment]
@almereyda yes, this could be part of [couch-init2](https://github.com/maxlath/couch-init2)

**Comment by maxlath** [comment]
made a small [benchmark](https://github.com/maxlath/blue-cot/blob/master/benchmark/authentification.js)
* 1000 cookie get: 6.169ms
* 1000 basic auth get: 1354.313ms
