### ISSUE TITLE
include the ISBN on the search results page

### ISSUE THREAD

**Issue by chadwhitacre** [inventaire/inventaire#69]
I've started adding books to my inventory—it's fun! :-)

It's tedious to type in an ISBN, so I'm finding it easiest to search for the title and then double-check the ISBN, but to see the ISBN I have to click through to "> more details," which is slowing me down.

P.S. I recognize that this would probably be much easier with a smart phone and a scanner app.

**Comment by maxlath** [comment]
hey @whit537, very glad you like it :D
this could easily be done indeed, but there is an ongoing work that might alter the expected benefits: I'm restructuring the book data model to have a better handling of Works > Editions hierarchy (following what is happening in [Wikidata books project](https://www.wikidata.org/wiki/Wikidata:WikiProject_Books)). The consequence will probably be that searching by title or author will return Works as results, behind which will be gathered all the different editions and there associated ISBNs: when there is only one edition, that shouldn't be a problem to display it straight from the search results page, but I'm more concerned for Works implying many editions, where it might end up being a mess... we will see then :)

**Comment by maxlath** [comment]
closing for now, has we invite users to use the scanner when they have a book with an ISBN
