### ISSUE TITLE
Error when adding publisher to edition

### ISSUE THREAD

**Issue by AutomCoding** [inventaire/inventaire#708]
When I search for a publisher to add to an edition, I get this error after entering the first character.

![Screenshot_20240111_093317](https://github.com/inventaire/inventaire/assets/40275136/a09e931d-b762-4563-a2d1-f3fa8f868e1e)

**Comment by AutomCoding** [comment]
Update: pasting in the Wikidata id has the same result.

**Comment by maxlath** [comment]
That bug was introduced by #698 and should now have been fixed by e06150694. Thanks for reporting!
