### ISSUE TITLE
Unable to perform password reset, account locked

### ISSUE THREAD

**Issue by Astralius** [inventaire/inventaire#709]
I can't log onto my account. Every time I want to reset password, I receive an e-mail with the password-reset link (correct):
![image](https://github.com/inventaire/inventaire/assets/6178718/72bc1ee0-026d-4890-9bcb-231bc299dc0c)

but when I click it to actually reset my password, I end up with following error:
![image](https://github.com/inventaire/inventaire/assets/6178718/971615b6-a387-4fbc-be8d-03e53ca6dd98)

I get it every single time I try to reset my password.
Tested several times, on different days and with two browsers (I assume this is browser-independent):
- Chrome ver. 120.0.6099.216 (64-bit)
- Edge ver. 120.0.2210.121 (64-bit)

**Comment by maxlath** [comment]
It appears something in your setup (mail client maybe? or the browser trying to check if its better to use ipv6 or ipv4, and http1.1 or http2) is making HEAD requests to the `/api/token?action=reset-password` endpoint, which consumes the token before your browser has the time to do its GET request. I disabled HEAD requests on this endpoint 0cf9a9f23 so now that should work, can you give it a new try? If it still doesn't work, we could try to not delete the token directly after the first GET request, but after a delay, or after the password has been successfully updated.

**Comment by Astralius** [comment]
@maxlath yes, that did the trick! I managed to reset password successfully.
