### ISSUE TITLE
add user and groups inventory RSS feeds

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#71]
I guess it would simply be about:
- fetching the data from the existing JSON API
- converting to RSS (or Atom?) with some lib
- serving it from some endpoint

Endpoints possibilities:
- `https://inventaire.io/api/feeds/public?user={userid}`
- `https://inventaire.io/api/feeds/public?group={groupid}`

Then actually, we could even have private feeds using [Basic Auth urls](https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding):
- `https://username:password@inventaire.io/api/feeds?user={userid}`
- `https://username:password@inventaire.io/api/feeds?group={groupid}`

Or à la Github using tokens?
-  `https://github.com/maxlath.private.atom?token=BlaBlajazgzagJnCqYMsaz7VrCL2D2C8YMwA==`

**Comment by maxlath** [comment]
on the RSS vs Atom conversation:
- [Reddit: Switching from RSS 2.0 to Atom 1.0](https://www.reddit.com/r/changelog/comments/428vdq/upcoming_reddit_change_switching_from_rss_20_to/)
- [Accéder au flux RSS d’un compte Diaspora](https://tuxicoman.jesuislibre.net/2016/11/acceder-au-flux-rss-dun-compte-diaspora.html?pk_campaign=feed&pk_kwd=acceder-au-flux-rss-dun-compte-diaspora)

**Comment by maxlath** [comment]
on Auth:
* Github post on [Token Private Feeds](https://github.com/blog/16-token-private-feeds)

**Comment by maxlath** [comment]
another social network with Atom feeds: [Diaspora](https://framasphere.org/public/maxlath.atom)

**Comment by jum-s** [comment]
Considering the title of the issue, this feature is complete.
The PR related can also be merged. 
We can start another issue/PR for nearby feeds and the other

**Comment by maxlath** [comment]
@jum-s merged! :fireworks: 
so basically, one new issue/PR couple per [TODOs](https://github.com/inventaire/inventaire/pull/78#issuecomment-279163550)?

**Comment by jum-s** [comment]
One issue, One branch, One PR, One merge
For me, the best way to keep it archivable & readable in the future

**Comment by jum-s** [comment]
then is you really want to you can link issues together, you can state that this new issue is the continuation of this former one

**Comment by maxlath** [comment]
@jum-s the new issues: #82 and #83

**Comment by maxlath** [comment]
so we can now close that one
