### ISSUE TITLE
Wrong Goodreads property for series

### ISSUE THREAD

**Issue by AutomCoding** [inventaire/inventaire#711]
When editing a series, the label for [P8383, Goodreads work ID](https://www.wikidata.org/wiki/Property:P8383) is shown instead of [P6947, Goodreads series ID](https://www.wikidata.org/wiki/Property:P6947).

I have not tried if it edits the correct property on Wikidata, but it does not fetch P6947 values already entered on Wikidata.

**Comment by maxlath** [comment]
Indeed! That should now be fixed, following https://github.com/inventaire/inventaire/commit/ba03cca https://github.com/inventaire/inventaire-client/commit/9d3795a and https://github.com/inventaire/inventaire-i18n/commit/8a501cd
