### ISSUE TITLE
Add a comment on an element

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire#717]
This comment would have its own table server side (document would be with an `elementId` key).

**Comment by maxlath** [comment]
Why not just a text field like `details` or `notes` on items? Is there any metadata specific to the comment that wouldn't make sense to have on the element document?

**Comment by jum-s** [comment]
To be more granular about multiple comments of the same element (?) 

2 examples: 
- having a comment's timestamp would allow to have comment's replies or to sort by newest comment, this comment time could be derived from the element timestamp but one may add comment at a different time than creating an element.
- some form of upvote could be attached to each comment
many other things could that will arise when comments in use (a tagging system?).

That said, im not against KIS text field either, i just imagined it with a table, but maybe it too much.

**Comment by jum-s** [comment]
Lets start by a textfield for the moment, the element being the timestamp and entity URI link to find the comment

**Comment by jum-s** [comment]
solved with https://github.com/inventaire/inventaire/pull/751
