### ISSUE TITLE
from coffeescript to ES6+

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#72]
Inventaire started as [a love affair with coffeescript](https://github.com/inventaire/inventaire/wiki/CoffeeScript) but it's not a definitive thing. While I don't mind using technologies that were trendy more than 6 months ago, there are real incentives to move the whole project to standard JS, ES6 and above.
## Reasons to stay with CS
- on the client side, **you need a transpiler anyway**. Browsers are not ready yet for pure ES6, and when they will be, they won't be ready for ES7, etc.
- **cleaner code** thank to meaningful indentations, beautiful [switch statements](https://github.com/maxlath/wikidata-sdk/blob/master/src/helpers/simplify_claims.coffee#L31-L38), comma-less/bracket-less objects (look at those [factory functions](https://github.com/inventaire/inventaire/blob/dev/server/controllers/relations/lib/parse_relations.coffee#L7-L11) <3), clean loops
- the existence operator `?`
- ~~CS is currently the fastest way for this project main contributor (hello :)) to get his ideas into code. But that's a vicious circle isn't it?~~
- ~~moving to ES6 modules would make [`universalPath`](https://github.com/inventaire/inventaire/blob/master/config/universal_path.coffee) impossible (see [ES6 variable import name in node.js](http://stackoverflow.com/questions/29168433/es6-variable-import-name-in-node-js))~~ *actually, we wouldn't be forced to use the ES6 module syntax, the CommonJS flavor would still be an option*
- arrow functions that aren't binding the context and giving the `arguments` object that [horrible/inconsistent behavior ES6 arrow functions](http://stackoverflow.com/questions/33288998/do-es6-arrow-functions-have-their-own-arguments-or-not) give
## Reasons to move to ES6+
- **Having a language known by way more people**. Despite the fact that _CS is just JS_, it isn't obvious to the new comers, making it less likely for them to jump in the code
- **Not having a language denigrated by the whole community**. Yep, that's sad, but new learners are largely discouraged to learn CS by the community, and while one might think this is totally disproportionate, you got to pick your fights
- With such a bad press, we can expect less and less support for CS, in JS tools in general (that `--coffee` flag in test tools, etc), but also in CS specific tools (coffeelint)
- leave CS kind of toxic governance for the TC39 bunch of java-lovers... hurraaay... :p
- NodeJs is ready for ES6: yeah destructive assignments \o/
- ES6 modules [tree-shaking](https://blog.engineyard.com/2016/tree-shaking) and other static module dependencies analysis goodies
- `const`, `let`, with possible performance benefits in the future, and less [lexical scoping issues](https://gist.github.com/AsaAyers/d09e4de118b8d6b5e2d8fa3e38e496e0#lexical-scoping-and-variable-safety)
- end the confusion between some CS and JS syntax: the `of` operator among others
## Conclusion

Moving to ES6+ seems quite unavoidable, but the benefits are only slowly unfolding. ES6 module tree-shaking for instance depends on all the dependencies to have moved to ES6 modules syntax. Given the important amount of work this migration would cost, let's give it time: I don't see it happen in the 6 to 12 next months. In the meantime, if you need help to get started with contributing in coffeescript, feel extra welcome to ask for help on anything! And who knows, maybe in 12 months CS will be all the rage again... ;)
## Resources
- [Moving to ES6 from CoffeeScript](https://gist.github.com/danielgtaylor/0b60c2ed1f069f118562)

**Comment by maxlath** [comment]
And while we are at it, we could wait for the [TypeScript](http://www.typescriptlang.org) vs [rtype](https://github.com/ericelliott/rtype) to settle: if we could get types annotations without falling back into a non-standard JS, that would be great. Food for thoughts: ["Static types are overrated"](https://medium.com/javascript-scene/the-shocking-secret-about-static-types-514d39bf30a3)

**Comment by maxlath** [comment]
## Article
* [Converting a large React Codebase from Coffeescript to ES6](https://blog.bugsnag.com/converting-a-large-react-codebase-from-coffeescript-to-es6/)
## Tools
* [decaffeinate](http://decaffeinate-project.org/)
* [standard](https://github.com/feross/standard)

**Comment by jum-s** [comment]
considering coffee is "just javascript"
considering javascript today is es6 and some coffee syntax is used in it `=>`
considering [coffee 2](http://coffeescript.org/announcing-coffeescript-2/)

when people say 'coffeescript is old, syntax is wierd', then a radical position can be : if people select project-to-contribute-to based on a language/syntax, because they are monoglot. It's fine, I hear it, but my opinion is based on how comfortable the group can be with this codebase. [some](https://github.com/inventaire/inventaire/blob/master/server/controllers/items/last_public.coffee#L9) syntaxic sugar makes it very easy.

why we need a clean readable short typing system : internal libraries "should live in a beautiful world of pre-validated inputs, free of all the trauma of having to take input from the external world" [source](https://github.com/inventaire/inventaire/pull/128#discussion_r152868753)
Now that this beautiful world is safe (through rough controllers), this world can self document at the micro-level, help ensure correctness, refactoring easier, and starting collaborating  together without fearing "wrong data". 
no matter where the project is going, typing  is very helpful in a autonomous/[adulthood](https://youtu.be/Lbcyyu8XB_Y?list=PLEx5khR4g7PLIaVkiIN3ukDhIFKIuGZGG&t=1494) app

**Comment by maxlath** [comment]
on that syntaxic sugar in particular, ES6 is pretty much there:
- coffee: `{ limit:someRenamedVariable, offset } = query`
- ES6 : `const { limit:someRenamedVariable, offset } = query`

Regarding typing, I agree that a lot of controllers ugly validation code could be replaced by a input schema definition, which in turn could be used to help generate the API documentation ([instead of manually updating it](https://github.com/inventaire/inventaire-api/tree/master/inv-spec/paths)). There are probably packages in the Swagger/OpenAPI ecosystem that could help us structure that, or we could take those as inspiration for a home-made version.

**Comment by jum-s** [comment]
this controllers things, is working now, no need to touch it
lets focus on the module/lib level of typing, through interfaces for example, seems to be a very readable solution that can be extracted cleanly somewhere. so that libs can freely living in a safe world

**Comment by maxlath** [comment]
nice article on how to [get the advantages of TypeScript without transpiling](http://seg.phault.net/blog/2017/10/typescript-without-transpiling/)
> Of course, using a non-standard language dialect also has its fair share of downsides. Using TypeScript in your project introduces a build step during development, diminishes compatibility with the broader ecosystem of existing tools that are designed to work with JavaScript, and requires all of your collaborators to learn the non-standard language features. Considering the rapid pace at which JavaScript is evolving, there are also some risks attached to locking yourself into a non-standard dialect.

sounds familiar ^^

**Comment by maxlath** [comment]
https://benchling.engineering/from-200k-lines-of-coffeescript-to-zero-making-decaffeinate-super-stable-4de0ca68d9bc

**Comment by NerOcrO** [comment]
Hi,
I want to contributing but not in CS: never ;)
It's old and no sense today.
