### ISSUE TITLE
Allow to delete a language title

### ISSUE THREAD

**Issue by nclm** [inventaire/inventaire#728]
I add books in several languages. Depending on the language I have the UI on, sometimes I get the title in the wrong language because Inventaire seems to set the default title field in the current language field. This is fine, but then I cannot remove the wrong language title, even after setting the right one alongside.

**Comment by HarmoniaAmanda** [comment]
This has been done, I think? We can now delete labels if one exists in another language

**Comment by nclm** [comment]
Yes I think too as well!
