### ISSUE TITLE
My shared book data can be modified by other users

### ISSUE THREAD

**Issue by emilbrasov** [inventaire/inventaire#742]
Hello,
I assume this is a bug and not expected functionality. Workflow:
1. Create a book in my Inventory.
2. Share the book with a group.
3. Another group member:
- clicks the book, opens the Book dialog.
-clicks the Work  field (book Title), opens the Work dialog
- clicks the PEN icon top right (Edit bibliographical Info), opens the book dialog.
Now the other user can modify the data for my books.
This should not happen, I should be the only one that can modify my Inventory data.
Thanks!

**Comment by maxlath** [comment]
Hi, that's not a bug: your inventory data can only be edited by you, but that inventory data is based on a mutualized bibliographic database that anyone can edit. It could be abused to change how your inventory is displayed*, but this is then a moderation issue, just like when someone vandalizes a Wikipedia article. Mistakes happen, but abuses are, so far, rare and easy to revert by admins.

* only the book titles, authors, and covers can be edited that what, but the visibility settings, transaction mode, details or private notes can only be changed by the inventory owner

**Comment by emilbrasov** [comment]
Great, now I understand how it works. Perfect, thank you, and totally agree with it.
