### ISSUE TITLE
entities activity give focus to the wrong resource

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#745]
ex: in the activity "A new edition has been attributed to [La Volte](https://inventaire.io/entity/wd:Q3213929): [Koinè](https://inventaire.io/entity/inv:27f5f8e89b15ab0504501d147c8dcfcb)" the [mastodon rendering](https://mamot.fr/@wd-Q3213929@inventaire.io/112297737471431831) gives focus to first link, here the publisher (La Volte), instead of what I think should be the focus, the edition
![Capture d’écran du 2024-04-19 17-59-43](https://github.com/inventaire/inventaire/assets/1596934/4b77eb3a-fa4b-4769-825d-1d47911de229)

This could be fixed by only setting the link to the edition (a link to the publisher can be found via the acitivtypub actor handle)

**Comment by jum-s** [comment]
This should have been solved by updating [weblate value](https://weblate.framasoft.org/translate/inventaire/server/en/?q=publisher_has_new_edition&sort_by=source&offset=1)

The same has been done for [collection](https://weblate.framasoft.org/translate/inventaire/server/en/?q=collection_has_new_edition), [subject](https://weblate.framasoft.org/translate/inventaire/server/en/?q=subject_has_new_work) and [author](https://weblate.framasoft.org/translate/inventaire/server/en/?q=author_has_new_work&sort_by=source&offset=1).
