### ISSUE TITLE
Allow subclasses of publishers

### ISSUE THREAD

**Issue by AutomCoding** [inventaire/inventaire#749]
I got the invalid type error when adding Q10503565 to an edition.

I suspect it's because Gehrmans is only instance of subclass of a publisher. [The _publisher_ entity page](https://inventaire.io/entity/wd:Q10503565) redirects to [the _main subject_ page](https://inventaire.io/entity/wdt:P921-wd:Q10503565) so it isn't being recognized as a publisher.

**Comment by maxlath** [comment]
Related issue: #414

**Comment by maxlath** [comment]
Fixed by #784
