### ISSUE TITLE
Adding a book manually with simplified UI containing most important Edition and Work fields in same window

### ISSUE THREAD

**Issue by emilbrasov** [inventaire/inventaire#750]
I added a lot of older books manually, that cannot be found by their ISBN number in any database. 
I did that by using Add Books -> Import -> Manually enter ISBN number in the "Import from a list of ISBNs" field, then "Create new work" for the missing ISBN, then click "Create selected Books".
The field with "Books successfully added to your inventory" appears. 
Clicking on "View book" button sometimes triggers a simplified UI that lets me add the most important fields from Edition and from Work, which helps a lot in speeding up the manual process. What I cannot figure out, is how to always acces this UI, I don't understand why sometimes appears and most of the times the UI is the same as clicking on a book in the home screen.
Is there a rule that would trigger this UI, when adding using the above process?
Thanks!

**Comment by jum-s** [comment]
Hi,
Problem is coming from [those lines](https://github.com/inventaire/inventaire-client/blob/main/app/modules/inventory/components/importer/candidate_actions.svelte#L36-L43). It feels like a bug, as the book doesnt look like its been added to your inventory despite being part of the "Books successfully added to your inventory".

To confirm this intuition, could you provide the URL you have been redirected to when clicking on "View book" button ? Ideally providing the URL the "View book" button redirect to (hovering the button) ?

Also, when you arrive in the UI you would like (not the home screen), in that case, has the book rightfully been added to your inventory ?

Thanks for the feedback

**Comment by emilbrasov** [comment]
Hello and thanks for the quick reply!
I'm redoing the steps here:
1: Add a book manually that is not in the ISBN database and give it a name:
[image: image.png]

2. Click on "Create Books" . Result:
[image: image.png]
Link from the button "View Book":
https://inventaire.io/items/80492804a7d892a594a6c69ee94d11a2

3. Clicking on View Book opens this dialog:
[image: image.png]

In order to add details from here, there are a lot of clicks needed.
I can not reproduce anymore the behaviour where the simplified Dialog
appeared with Edition and Work fields in one view.
If I close this dialog now, I can see the book in my library:
[image: image.png]

Does this information Help?
I'm using Edge Browser Version 126.0.2592.56 (Official build) (64-bit).
Please let me know how I can further help.
    Regards, Emil C.

**Comment by jum-s** [comment]
I cannot reproduce the behaviour either. 

For information, the "edit edition" UI is popping up as a link because the item (the exemplar book in your inventory) has not been created, therefore redirecting to an edition URL `/users/${username}/inventory/${edition.uri}`. 

But in any case, it is 4 clicks away to edit data about the book again, while the link could easily be built. So, I tried an improvement with `main`'s commit `5fafa592f`, which adds a button to edit data.

![2024-06-28_10-37](https://github.com/inventaire/inventaire/assets/5363918/cfc13990-2683-4019-9b49-7d86d90b1930)

Some cosmetics may be discussed ("Edit edition" is too general for a very different context link, buttons could be regrouped in an actions dropdown menu), but the idea is here.

**Comment by emilbrasov** [comment]
Hi again,
Thanks for the feedback, I see that the button *Edit Edition* is already
there:
[image: image.png]
and redirects to:
[image: image.png]
Which is PERFECT !!!


Could you please add another button, called "*Edit Work*", that redirects
to this page:
[image: image.png]
Like this we can add in 2 clicks both Edition details and Author details.

Thanks a lot, huge help!
Emil

**Comment by jum-s** [comment]
Unfortunately, it's not as easy to add a "work button" as a book may have several works, which would mean a lot of buttons then, so a dropdown.
You can open an issue for the matter if you feel like it.
Thanks for the feedback!

**Comment by emilbrasov** [comment]
Thank you for the clarification and for the help!
    Regards, Emil C.
