### ISSUE TITLE
Expose more social networks for authors

### ISSUE THREAD

**Issue by nclm** [inventaire/inventaire#755]
Hello. So for now, Inventaire shows these fields on author’s profiles for their social networks: Twitter, Instagram, Facebook, YouTube, Mastodon.

That’s all good, I do run into a lot of authors that are on other networks (and might have their main social media presence there), so it could be interesting to display them in Inventaire as well.

Mostly seeing:
* LinkedIn [(P6634)](https://www.wikidata.org/wiki/Property:P6634)
* Bluesky [(P12361)](https://www.wikidata.org/wiki/Property:P12361)
* Threads [(P11892)](https://www.wikidata.org/wiki/Property:P11892)

Of course there are a lot of other networks, and it would also be nice to feature more of the non-profit ones (or have a general “Fediverse handle” property but that’s on Wikidata side), but these three seems popular enough among writers that it would make sense to have them displayed.

**Comment by maxlath** [comment]
Done in https://github.com/inventaire/inventaire/commit/72a459, https://github.com/inventaire/inventaire-client/commit/67e8a2e, and https://github.com/inventaire/inventaire-i18n/commit/ff09896

**Comment by nclm** [comment]
Thanks!
