### ISSUE TITLE
Add P7937 (work format)

### ISSUE THREAD

**Issue by HarmoniaAmanda** [inventaire/inventaire#766]
Please add the property P7937 which is now the place on Wikidata where we indicate if something is a short story, a novella, a novel, a poem, a play, a short story collection, etc.

Having it visible on inventaire would help a lot when short stories and collections are named the same, for example.

**Comment by maxlath** [comment]
Closing as it's a duplicate of https://github.com/inventaire/inventaire/issues/563 but thanks for bumping it up!
