### ISSUE TITLE
Delete Q43334491 from the allowed values for P7937

### ISSUE THREAD

**Issue by HarmoniaAmanda** [inventaire/inventaire#776]
During my cleaning up of P7937 and P136 I found this case. It was used a lot, so ended in the allowed values list, but going through all the items using it, they were absolutely all wrong. Currently no Wikidata item has this value for P7937, and it should deleted from inventaire too.

(Also I will probably create soon a Wikidata entry for "collection of novels", because that's a case relatively frequent on inventaire, and it will need to be added in the allowed values.)

**Comment by maxlath** [comment]
Thanks! Done in d1124ecda
