### ISSUE TITLE
Allow unfinished works as works

### ISSUE THREAD

**Issue by HarmoniaAmanda** [inventaire/inventaire#787]
There are a number of unfinished works which are actually published, so it would be great if P31:Q108419088 was allowed as a work and not a subject on inventaire.

An example would be Q7765010, which has been published in several anthologies and collections even though it's an unfinished draft.

**Comment by maxlath** [comment]
As for  #788, this should soon be fixed by #784, which will make instances of (P31) subclasses of (P279) Wikidata items known to be classes of works be typed as works too

**Comment by maxlath** [comment]
Fixed by #784
