### ISSUE TITLE
Allow letters as works

### ISSUE THREAD

**Issue by HarmoniaAmanda** [inventaire/inventaire#788]
There are a number of letters which are actually published, so it would be great if P31:Q133492 was allowed as a work and not a subject on inventaire.

An example would be Q108368541, which has been published in several anthologies and collections.

**Comment by maxlath** [comment]
This should soon be fixed by #784, which will make instances of (P31) subclasses of (P279) Wikidata items known to be classes of works be typed as works too

**Comment by maxlath** [comment]
Fixed by #784
