### ISSUE TITLE
enable goodreads Import

### ISSUE THREAD

**Issue by aberlin** [inventaire/inventaire#80]
Hi I could use an easy form to Import my Bookshelf  from [goodreads](https://www.goodreads.com/)
A Sync would be the best. Just like in [this](https://github.com/eleybourn/Book-Catalogue/wiki) Android app.
HTH

**Comment by maxlath** [comment]
hello @aberlin!
I have been working on [data importers](https://github.com/inventaire/inventaire-client/blob/943fe11140ade7a0f966aebbc9097d9d974e3cf8/app/modules/inventory/lib/importers.coffee) earlier in 2016, but was waiting for the incoming [book data model revolution](https://trello.com/c/doDQZ987/99-restructure-the-database-to-allow-more-detailed-data) before updating it and publishing it, which should happen soon-ish. It's a one time import though, not keeping in sync: do you have documentation on how to keep in sync with goodreads?

**Comment by maxlath** [comment]
@aberlin it is now possible: https://inventaire.io/add/import
