### ISSUE TITLE
split databases per document type

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#85]
some document types are being mixed in common databases. From [server/db/couch/list.coffee](https://github.com/inventaire/inventaire/blob/2c3ddea28236177d5d04e9fb0b06ce125015a762/server/db/couch/list.coffee):
```js
users: ['user', 'relations', 'groups', 'invited']
entities: ['entities', 'patches']
```

This could [degrade performance at scale](http://www.dimagi.com/blog/what-every-developer-should-know-about-couchdb/), without bringing much value: the original idea was to use [linked documents](http://docs.couchdb.org/en/2.0.0/couchapp/views/joins.html) and ease maintenance (less databases to take care of). This last (weak) point on maintenance is already being counter-balanced by the additional care having several types in a single databases requires when performing a [migration](https://github.com/inventaire/inventaire/blob/2c3ddea28236177d5d04e9fb0b06ce125015a762/scripts/migrator).

**Comment by maxlath** [comment]
done for groups: 2cd3130

**Comment by maxlath** [comment]
done for patches: 9f3b786

**Comment by jum-s** [comment]
done according to [the new list](https://github.com/inventaire/inventaire/blob/master/server/db/couch/list.coffee)  
`patches` & ` groups` has its own type
