### ISSUE TITLE
use libraries data to automatically merge works and authors

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#87]
Currently, every time an edition entity is created, unless an existing work entity is provided, it creates new work and authors entity to be associated with. This creates many duplicates that need to be merged, but this obviously can't be done just by comparing strings, as there is a certain variety of name notations, and there are homonyms. Fortunately, some libraries are now giving access to their graph databases, which would allow to automatically merge entities with a significantly higher degree of trust.

I have been starting to play with the [BNF SPARQL endpoint](http://data.bnf.fr), which seems to be a good place to start, but there are many more, and they are progressively being [federated with Wikidata](https://www.mediawiki.org/wiki/Wikidata_query_service/User_Manual#Federation): we could probably take advantage of that!

**Comment by maxlath** [comment]
suggested by @atomotic: http://classify.oclc.org/classify2/api_docs/index.html

**Comment by jum-s** [comment]
work in progress thx to `d813259`
as bnf & wikipedia are now check to deduplicates entities

**Comment by atomotic** [comment]
i don't remember if i suggested https://github.com/atomotic/isbn-authors

**Comment by jum-s** [comment]
done with tasks implementaion through a [reconciler](https://inventaire.io/users/reconciler/contributions) user
