### ISSUE TITLE
Different books link to the same book

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#90]
I have encountered a big issue. I was going through my inventory to update the information of my books when I saw on https://inventaire.io/entity/inv:aea555cb4000c73f30e5288af10e16c8 that there were several book seen as editions link to one book.

In this case, the volumes 12, 13, 14 et 15 of Bakuman are seen as editions of the volume 12. What is expected is to have a book for each volume.

**Comment by maxlath** [comment]
this is weird, those editions should indeed have one associated work each. The reasons of this issue I can think of:
* the server mistakenly assumed that those similar title where refering to several editions of a unique work
* a user mistakenly added editions to this work, assuming this was the Bakuman series page

It shouldn't be too hard to fix it, but can't be done from the user interface, I will do this in the coming days.

This kind of issues are to be expected given the way our knowledge base is build - with a mix of server assumptions and open human contributions -, we should just progressively get better at tackling those, making them less likely, and easier to fix :)

**Comment by thewholelifetolearn** [comment]
If it is a user mistake, it could be because there is no big difference display between series and a work. Even with an edition.

Perhaps, should there be a manager kind of users. They could correct things, manage duplicates, etc.. That would give some hassle less for the administrator (in this case, you).

**Comment by thewholelifetolearn** [comment]
There is the same issue with the volumes 3 and 9: https://inventaire.io/entity/inv:aea555cb4000c73f30e5288af10cbe01

**Comment by thewholelifetolearn** [comment]
Same thing with volumes 36 and 37 of "Prince du Tennis": https://inventaire.io/entity/inv:aea555cb4000c73f30e5288af1091208

**Comment by maxlath** [comment]
I fixed those different cases but we should probably let this issue opened in case more come and until we can get it fixed: I'm now pretty sure that it's the server that is too aggressive at matching editions to a common work when the title and the authors names match; it works for most books but visibly not for manga and series where works are more often titled on the pattern "serie name - volume x"

**Comment by thewholelifetolearn** [comment]
Indeed, I don't know what are the sources of the information, but in the cases of comic books series or manga series, the names are often "series name -  series name" or just "series name".  
That is the reason I'm renaming a lot of them to "series name - volume[ - name]".

Thank you for making the changes. I will let the issue open if the case happens again.

**Comment by thewholelifetolearn** [comment]
I just encountered the same problem for some volumes (2, 3, 5, 6) of the comic books of "Joe Bar Team": https://inventaire.io/entity/inv:9cf5fbb9affab552cd4fb777129f7331

**Comment by maxlath** [comment]
just fixed the Joe Bar Team case

**Comment by thewholelifetolearn** [comment]
I have re-encountered the issue with 2 manga: Tome 23 and 24 of the Team Medical Dragon series  
https://inventaire.io/entity/inv:71b4f804c097431886e9ea2d343638ba

**Comment by maxlath** [comment]
as I'm currently working on [composite editions](https://github.com/inventaire/inventaire/issues/93), I'm considering unlocking the possibility to change the work an edition is bound to, so solving this kind of case should soon get as simple as:
* creating a new work to associate to the wrongly attributed edition, if it doesn't exist
* editing the edition work property
I will let you know when it's online

**Comment by maxlath** [comment]
@thewholelifetolearn as announced in the previous comment, it is now possible to edit an edition 'edition of' ([`wdt:P629`](https://www.wikidata.org/wiki/Property:P629)) property, could you give it a shot to fix the issue with Team Medical Dragon Tome 24?

**Comment by thewholelifetolearn** [comment]
I can indeed add a work to an edition but I don't understand how it should work. How do I create a new work from this page?

**Comment by maxlath** [comment]
you can't from the work's page, but you can create it from the [series' page](https://inventaire.io/entity/inv:71b4f804c097431886e9ea2d343e3759)

**Comment by thewholelifetolearn** [comment]
Ok. I will try that in the next days.  
But why didn't it propose any work when I entered "Team Medical"? It should have proposed the other works of the serie at least.

**Comment by maxlath** [comment]
indeed! it was due to a [now-updated search engine nginx config](https://github.com/inventaire/wikidata-subset-search-engine/commit/adf2728cb4800b3e9e59008a95302c93bf7209fb), now it seems to work

**Comment by thewholelifetolearn** [comment]
I works. The work-flow isn't very fluid (first create a work in the series, then change the work of the edition) but at least the possibility exists!

**Comment by thewholelifetolearn** [comment]
With this solution, I consider this issue as closed
