### ISSUE TITLE
error in repository

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#94]
When I clone the repository I have an issue that comes up:
* Invalid path: db/couchdb/migrations/logs/inventory-2014-11-10T14:23:18.897Z.json

Because of this, I can't have access to the repository in local through git. I have access to the files but I cannot integrate the modifications.
From what I understand, I searches for a file that is not saved in the repository because the directory is ignored in git.

**Comment by maxlath** [comment]
could you post the logs of the failing script? a file and a line number would really help to see where this can come from :)

**Comment by thewholelifetolearn** [comment]
No script is failing. I just want to clone the repository on my computer. See screenshot for more information

![image](https://cloud.githubusercontent.com/assets/823564/26833618/46bf463e-4ad3-11e7-9e65-7ef1bd4e714a.png)

**Comment by maxlath** [comment]
weird, I can't reproduce the issue, are you on Windows? It could be an issue with the filename containing commas. Anyway, I removed the folder (5865da8), hopefully fixing this problem

**Comment by thewholelifetolearn** [comment]
Yes, I was cloning under windows. I just cloned again the repository and it works fine. Thanks
