### ISSUE TITLE
Ordinal series show only on some works on the inventory page

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire#96]
The ordinal of a work in series isn't shown in all cases on the inventory page.  
See screenshots for examples:

![image](https://user-images.githubusercontent.com/823564/27260617-e0cebc58-5430-11e7-8210-26e4c6389bc7.png)

![image](https://user-images.githubusercontent.com/823564/27260621-f4309730-5430-11e7-9a08-3c7157ebc46d.png)

![image](https://user-images.githubusercontent.com/823564/27260624-ffb4063c-5430-11e7-8e11-874ba8c3b71b.png)

**Comment by thewholelifetolearn** [comment]
I think this issue is related with the database when the property `rank` was renamed to `ordinal`

**Comment by maxlath** [comment]
possible, as I didn't do a migration, thinking the few pre-existing cases would progressively get fixed: if this is the case, any update on the work should trigger a snapshot data refresh on the item. I will have a look.

**Comment by maxlath** [comment]
yes, that was it apparently: after [adding a date of publication on isbn:9782723493703](https://inventaire.io/entity/isbn:9782723493703/edit), your item was updated with `.snapshot['entity:ordinal'] = 23`.
