### ISSUE TITLE
Adding an existing book collection

### ISSUE THREAD

**Issue by jollyrogers88** [inventaire/inventaire#97]
Hi math,

I've already created an spreadsheet of my whole library.

It would be great to have an import possiblity for CSV data; I could prematch the authors to their Q numbers.

**Your tool is great**, but when you don't have a barcode scanner (or old books [without ISBN](https://inventaire.io/entity/inv:c7ab027aa7e2654af81e9e6131c7a373)) the data input is just too slow.

**Comment by maxlath** [comment]
Hello @jollyrogers88, welcome here :)

That's indeed an identified need, but there are several difficulties:
* **parsing the custom formats**: it's already possible to [import data](http://inventaire.io/add/import) from several websites has those have (rather) stable formats, but importing from random csv files seems more complex. A work around would be to simply collect all the ISBNs that can be found in a given file, and offer to import those
* but **handling the ISBNs for which no data can be found** is still rather painful (see late [issue on the import queue crashes](https://github.com/inventaire/inventaire-client/issues/100)). A way to make it less so would be to offer a workflow to efficiently input the missing data, but that could be quite some work to do all at once, and, at the moment, without the possibility to pause and resume later.

Easing large data import is part of a larger [mass edition](https://trello.com/c/vwMU57Ne/127-ease-large-inventory-edition) subject, for which there is a lot to do and that was rather under-served so far. A few subjects still have priority on it (like [being able to browse inventories with more criteria than the current chronological order of addition to the inventory](https://trello.com/c/wq1RCyuc/20-sort-books-by-author-genre-collection-publication-date)), but that could come in the next ones.

**Comment by jollyrogers88** [comment]
You could define a standard CSV format.

**Comment by jum-s** [comment]
The best todo list has only one item, and you defined it max : "collect all the ISBNs that can be found in a given file"
through parsing headers label of a csv to match a regex of like `/isbn/i` then parse all match of ` /10\d | 13\d/ ` of this csv column and mass import ! with preview i guess would be necessary

**Comment by maxlath** [comment]
we do already [have this regex at hand](https://github.com/inventaire/inventaire-client/blob/23dc7eee908544acd6387b2a2e3652e859eace8e/app/lib/shared/isbn.coffee):
```js
/^(97(8|9))?\d{9}(\d|X)$/
```

**Comment by maxlath** [comment]
hey @jollyrogers88, the ISBN importer is now online, so if your CSV happen to use those, could you try using it and tell us how it goes?
